### ISSUE TITLE
[Enhancement] Add a file extension that updates QEMU of UTM (for jailbroken iDevices only)

### ISSUE THREAD

**Issue by IIWare** [utmapp/UTM#1198]
Sometimes, it may be hard to just update QEMU in UTM, so there can be a file extension that's called ***.udqemu** for example **QEMU_v5.2.0.udqemu**, ("ud" stands for update in the file extension) so someone can just click on it in the files app, and then update the QEMU system from 5.1.0 to 5.2.0 for UTM, by extracting the updated QEMU system files to the UTM QEMU path and then deletes the old QEMU system files. so hopefully this could be implemented, thanks.

**Comment by osy86** [comment]
Even in jailbroken iOS, this is not possible without massive hacking due to sandboxing and hardened runtime.

Even if it were possible, it won't work due to all the changes to QAPI (which is baked in). Just look at the amount of changes needed to update from 5.1.0 to 5.2.0. https://github.com/utmapp/UTM/commit/5fa2de4b45f92b335d037714688afa69adb23997
