### ISSUE TITLE
Improve memory usage monitoring

### ISSUE THREAD

**Issue by cs-sugar** [utmapp/UTM#120]
IPad Pro 11 inch, 64GB ROM, 4GB RAM
When the virtual machine memory is set to more than 1.9GB, turn on the virtual machine, the software will flash back. When the virtual machine memory is set to 1.9GB, after a period of time, it will crash, white screen, and ask for help.

**Comment by WindowsBetaTest** [comment]
IOS devices have a high memory consumption, about 60% - 80%.

The memory allocated to VM in UTM should be about 1024MB, otherwise it will crash

**Comment by Shawnjoseph2001** [comment]
Possible enhancement: change the input for memory from a numerical input to a slider so only certain values are allowed

**Comment by ThatsNiceGuy** [comment]
I found that 1.5GB of allocated RAM is the highest i can go on my identically specced iPad

**Comment by conath** [comment]
According to [this memory test](https://stackoverflow.com/a/15200855) carried out by lots of folks on StackOverflow, the maximum amount of memory an app can use varies by device. 50% *seems* to be low boundary for out of RAM crashes on iOS 11 and later, so it might be a good idea to tell the user about that. Currently the estimated JIT cache is .5 times the guest RAM according to [VMConfigSystemViewController.m](https://github.com/utmapp/UTM/blob/2b3d10c6dbb08d08595934008fe7da2940caec6d/ConfigurationViews/VMConfigSystemViewController.m). This cache size needs to be added to the amount of RAM requested for the virtual machine to get the actual memory usage of the app, which is why your iPads crash at 2 out of 4 GB used.

Currently, the configuration code warns you if your VM will need more than 80% of system RAM. I think it should be a two stage warning, like >50% danger, >70% not possible. So we have:
```objc
NSUInteger jitNumerator = 3;
NSUInteger jitDividend = 2;
NSUInteger estRAM = jitNumerator * chosenAmount / jitDividend;
bool warnAboutRAM = estRAM >= systemRAM / 2;
bool outOfRAM = estRAM >= systemRAM * 5 / 7; // 5/7 == 0.71
```

Paging @osy86 who wrote the warning code, what do you think?

**Comment by osy86** [comment]
Yeah, but does ios always send a low memory notification first or will it sometimes kill without any warning?

**Comment by ntindle** [comment]
See also https://stackoverflow.com/a/59273682

**Comment by osy86** [comment]
> Possible enhancement: change the input for memory from a numerical input to a slider so only certain values are allowed

I don't want to do this because 1) .utm files can be shared amongst multiple devices and 2) we want power of twos for max OS support.

**Comment by conath** [comment]
> > Possible enhancement: change the input for memory from a numerical input to a slider so only certain values are allowed
> 
> I don't want to do this because 1) .utm files can be shared amongst multiple devices and 2) we want power of twos for max OS support.

You could get integers from the slider and use them as the power of two. E. g. slider goes from 6 (2^6=64MB) to 2^12 (4GB). I'd propose to have the slider as an additional way to input the amount of RAM, and to allow manual editing just like before.

**Comment by osy86** [comment]
Ideally we have something like VMware that lets you choose powers of two but "common" values like 3GB, 4GB, 5GB, etc as well as lack of stuff like 2MB or 4MB. Anyways I think it's a lot of work for something that ultimately doesn't add too much value.

**Comment by luca19999** [comment]
hello do you think it can be possible to run window or mac os with good performance on the new ipad pro 8gb or 16 gb of ram??

**Comment by luca19999** [comment]
I mean how muh of Ram can be allowed to UTM with the new ipad pro
