### ISSUE TITLE
Double tap Apple Pencil to switch to right click

### ISSUE THREAD

**Issue by osy86** [utmapp/UTM#199]

**Comment by conath** [comment]
I [implemented](https://github.com/utmapp/UTM/pull/297) the very basic behavior as follows: double tapping the Apple Pencil 2 ([API doc](https://developer.apple.com/documentation/uikit/uipencilinteractiondelegate/3039595-pencilinteractiondidtap?language=objc)) enables "one time right click" mode. In this mode, tapping the screen with a single touch like Pencil then results in a right click triggered instead of left click and the mode is disabled.

Unfortunately, I don't have an iPad with Apple Pencil 2 support. So I can't test if it really works. I mocked it by setting the mode when two-finger-tapped and then tapping with my Apple Pencil 1, which works:

```swift
- (IBAction)gestureTwoTap:(UITapGestureRecognizer *)sender {
    if (sender.state == UIGestureRecognizerStateEnded &&
        self.twoFingerTapType == VMGestureTypeRightClick) {
//        [self mouseClick:SEND_BUTTON_RIGHT location:[sender locationInView:sender.view]];
        pencilForceRightClickOnce = true;
    }
}
```

I opened [PR 297](https://github.com/utmapp/UTM/pull/297) about this.
