### ISSUE TITLE
[UI] macOS QEMU arguments: entering only one new argument and clicking Save discards entered data

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2276]
**Describe the issue**
In VM Settings QEMU tab, additional arguments can be entered at the bottom of the list. If one enters some text and then clicks Save, the text isn't saved.

**Configuration**
* UTM Version: 2.0.19 (19)
* OS Version: macOS Big Sur 11.1
* Intel or Apple Silicon? occurs on both

**Workaround**
Enter your additional QEMU argument in the `New…` text field. Then tap TAB ⇥ key once. You will notice that an additional `New …` text field has appeared below your typed text. This means it is now safe to click `Save` and the argument will be stored.

**Comment by osy** [comment]
Hmm this may be annoying to do in SwiftUI but I’ll try.

**Comment by conath** [comment]
I haven't looked at what causes the bug exactly. From the behavior it seems [this workaround](https://github.com/conath/TheatricalMovieTrailers/blob/main/TheatricalMovieTrailers/Supporting%20Files/API%20Extensions/UIResponder%2BcurrentResponder.swift) might help: it allows you to force resign the current UIResponder even in SwiftUI.

**Comment by osy** [comment]
The current implementation uses `TextField("New...", text: $newArg, onEditingChanged: addArg)` to add an arg. `onEditingChanged` only is called when you press Tab or change focus. I'm not sure if forcing resign current UIResponder when clicking Save will call onEditingChanged because how it's implemented Save is "outside" SwiftUI. There could be some hacky solution with timers or to have a subscriber on newArg that saves the last edited value and on save if the last saved arg != that value and it's not empty then create a new argument.... Still feels poor to maintain.

**Comment by osy** [comment]
For the immediate future, I'll add some features that should make extra args not needed for booting macos. Then hopefully the next SwiftUI api changes will give us a solution.
