### ISSUE TITLE
What about App Exposé for iPad?

### ISSUE THREAD

**Issue by cheny0y0** [utmapp/UTM#2297]
What about App Exposé for iPad?

**Comment by conath** [comment]
Could you elaborate on your request? Are you referring to the [iPadOS 13+ feature](https://www.imore.com/how-open-multiple-app-spaces-ipad) that allows you to open multiple windows of the same app? In that case, it's a known issue that you can't run multiple virtual machines at once on iOS #9.

**Comment by osy** [comment]
Right this would depend on #9 which will not be implemented due to the complexity and low payoff. Running multiple VM instances will probably not work anyways due to the memory restrictions by iOS. Maybe in a future where XPC is allowed on iOS or QEMU is massively refactored or we no longer depend on QEMU this may be possible...
