### ISSUE TITLE
Clone VM without drives (light clone)

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2339]
Please add the option to clone a VM without cloning its drive images. As far as I know, the existing clone feature creates a copy of the VM including the image files. This is sometimes prohibitive because the VM hard disks can become quite large. 

This feature could greatly benefit the project because it would allow for easier sharing of VM configurations.

**Comment by adespoton** [comment]
My current process is to clone/share the config and then replace the image with a pre-formatted blank image of the appropriate type.  Because APFS can clone without using more space on disk, storage isn't an issue.  But the ability to share to an online repository and automatically strip PII (erase debug logs, replace disk images with an unformatted image of the same logical size) would be great.
