### ISSUE TITLE
No boot any iso

### ISSUE THREAD

**Issue by tolikes** [utmapp/UTM#2409]
**Describe the issue**
Dejo de funcionar al actualizar a al ultima versión, ahora no arranca ningún iso ningún floppy

**Configuration (required)**
* UTM Version: 2.0.25
* OS Version: iOS 14.2
* Device Model: iPhone 11
* Is it jailbroken (name jailbreak used)? Yes, Unc0ver
* How did you install UTM? 
Sideload 
**Crash log**

https://pastebin.com/x4fqkAPt

**Debug log**

https://pastebin.com/qvnjwgjJ

**Upload VM**
No se necesita

**Comment by conath** [comment]
From your debug log it looks like you're trying to boot a Windows ME installer. For this I'd recommend that you switch to the older virtual computer. To do this, go to the VM Configuration → System and change the System (where it says something about 2009) to `Standard PC (i440FX + PIIX, 1996) (alias of pc-i440fx-5.2) (pc)`.

There are further problems with your VM configuration, so I've gone ahead and created a new virtual machine that should work for installing Windows ME. It includes an up to 20 GB hard drive and some performance optimisations since you're on iPhone 11.

[Windows ME.utm.zip](https://github.com/utmapp/UTM/files/6239781/Windows.ME.utm.zip)

Please let me know if this solves your problem. 

By the way, the "crash log" you uploaded is in fact a "resource warning" type of log generated by iOS. These will continue to appear because, put simply, UTM is an unusually intense app compared to other iOS apps.

**Comment by tolikes** [comment]
Amazing
