### ISSUE TITLE
Works awful on Mac os 11.3

### ISSUE THREAD

**Issue by muratdk23** [utmapp/UTM#2412]
Network, graphics, mouse works awful. No stability at all. I hope you'll fix this soon.

**Configuration**
* UTM Version: 2.0.25
* OS Version: 11.3
* Intel or Apple Silicon? Apple Silicon

**Comment by osy** [comment]
Closing due to not enough information. You can reopen it if you provide information such as:

1) what vm are you running?
2) what specifically are the issues with graphics?
3) what specifically are the issues with mouse?
4) what specifically are issues with networking?
5) Attach debug and crash logs if the issues involve crashes/errors.
