### ISSUE TITLE
Boot order for floppy disks is not respected

### ISSUE THREAD

**Issue by boeckmann** [utmapp/UTM#2492]
**Describe the issue**
I can not install Win95b because after partitioning the hard disk I can not boot from floppy disk anymore. I think the cause is that the qemu bootindex command line parameter for the floppy disk is missing and so has the least boot order priority.

**Configuration**
* UTM Version: 2.0.27
* OS Version: Big Sur
* Intel or Apple Silicon? M1

**Comment by conath** [comment]
Can you please try reordering the drives in the Drives Configuration? It is supposed to try booting from the topmost drive first, and so on. So your floppy drive should be at the top of the list. Note that rearranging the drives clears any selected removable drives, so you need to browse to the files again.

**Comment by boeckmann** [comment]
Hello @conath, I already tried that and the floppy drive is at the first position of the list. But it does not get a bootindex parameter (see screenshot). Perhaps that is the problem?
<img width="317" alt="Bildschirmfoto 2021-05-07 um 12 04 28" src="https://user-images.githubusercontent.com/6333969/117434208-ae24c800-af2c-11eb-9cd7-2831604bfee5.png">

**Comment by boeckmann** [comment]
After further investigation I think that in function expandDriveInterface in file UTMqemuSystem.m there is a case missing for the "floppy" interface and therefore the bootindex priority (and generally the qemu -device parameter) is not generated.

**Comment by boeckmann** [comment]
I tried manually starting qemu via command line and setting the right boot priority via `bootindex`. It seams that the floppy device does not accept a `bootindex` parameter. That is in accordance to the qemu command line help, which does not list such a parameter.

The only way I got it working was via a `-boot` parameter. In my case `-boot acd` for boot priority Floppy, Drive C (hard disk), drive D (cdrom) and **removing all bootindex parameters** for the other devices. As long as ANY device has a bootindex parameter, the -boot command line parameter is ignored.

At the moment I am a bit stuck what could be a solution which works in every case.

**Comment by conath** [comment]
Thanks for investigating this issue. There have been other reports around the `bootindex` not working reliably, so this is a topic that will definitely be addressed.

For an immediate solution I suggest that you set the drive interface to `none` for all drives in your VM, and then add the `device` parameters manually in the QEMU section (scroll all the way down, there is a “new…” field.
This way all drives are tried for booting, as far as I know.

**Comment by conath** [comment]
I have added the `bootindex` to the floppy parameter in a fork. However that didn't work because QEMU doesn't support the `bootindex` for the `floppy` drive type (I'm assuming that that is why it has been left out)

Some time ago, the boot priority logic in `UTMQemuSystem` was switched from using the `-boot` parameter to using the `bootindex`. If compatibility with floppies is considered important to the project @osy, could a solution to this be to create a separate `UTMQemuLegacySystem` that handles these legacy edge cases? This would also streamline things by removing the existing special case in USB handling.

**Comment by osy** [comment]
I think you need to do bootindexA or something since floppy emulation has two drive slots.

**Comment by conath** [comment]
osy is correcy, there is a separate `bootindex` parameter for floppies ([source](https://bugzilla.redhat.com/show_bug.cgi?id=1337375#c5)).

The additional QEMU argument needed is `-global isa-fdc.bootindexA=X` were X is the index you want the floppy drive to have. If you have a second floppy in the machine, it's `bootindexB` instead of `bootindexA`. Adding this line in the QEMU tab would not help @boeckmann however because UTM currently auto-assigns the bootindex 0 to the first non-floppy drive in the VM. A temporary solution would be to set all drive interfaces to `none` and then add all the drive parameters manually, including the `bootindex`. I've verified that this works to boot from floppy first.
![manual-bootindex](https://user-images.githubusercontent.com/12073163/117585268-c9046180-b111-11eb-94df-37cf2027566c.jpg)

However I believe I have found an easy workaround for this and similar issues with the SeaBIOS not booting as expected. We could add a toggle to the System or Drives page that enables the boot menu:

`-boot menu=on` results in a few seconds of the prompt "Press ESC for boot menu." when the VM starts. If you press ESC, it will list all available boot devices. Otherwise, it will boot according to the `bootindex`.
![seabios-boot-menu](https://user-images.githubusercontent.com/12073163/117585284-db7e9b00-b111-11eb-83ab-2fa15330a43c.jpg)

I'll open a separate issue about the boot menu toggle.

**Comment by boeckmann** [comment]
The menu option `-boot menu=on` sounds really nice and would do the job for me! Would be great if that could be implemented.

**Comment by conath** [comment]
> The menu option `-boot menu=on` sounds really nice and would do the job for me! Would be great if that could be implemented.

I’ve opened #2504 about it. In the meantime, you can easily enable the boot menu yourself: simply put the `-boot menu=on` as a additional QEMU argument in the VM configuration. Click the QEMU tab and scroll all the way down, then paste it in the New… field.
