### ISSUE TITLE
ARM64 VM does not boot because EFI NVRAM is not persisted

### ISSUE THREAD

**Issue by CodeGrub** [utmapp/UTM#2503]
After installing the os the virtual machine reboots into the os menu and allows the use of operating system. Upon subsequent reboots you are dropped into a UEFI shell. And every time after the first reboot this happens.

**Comment by conath** [comment]
This happens because, when the VM first reboots after you install the OS it "remembers" the new installed OS boot settings from the installer. After you close the VM window, this is "forgotten" and the next time, it will try your first Drive instead. 

To fix it, make sure that the hard drive is the topmost drive in the VM Configuration => Drives. You can move it up the list with the up button on Mac or by tapping Edit, then rearranging on iOS. Alternatively, you could delete all other drives apart from the hard drive.

Feel free to reopen this issue if my suggestion does not fix the problem for you. In that case, please include the content of "Export QEMU arguments" from the QEMU tab in your reply. That way I can offer more suggestions.

**Comment by CodeGrub** [comment]
I should have mentioned I already tried rearranging drive order and deleting the installer drive. neither method fixed the problem.
[qemu command export.pdf](https://github.com/utmapp/UTM/files/6452507/qemu.command.export.pdf)

**Comment by conath** [comment]
I have tested an AARCH64 Kali Linux VM in UTM using the "UTM Logo EFI" from [here](https://github.com/utmapp/edk2) and it exhibits a similar problem. After the VM is powered off after installation, and then powered back on later, it doesn't detect the installed grub boot loader, and sits at a screen asking if you want to enter the boot menu.
<img width="1136" alt="Bildschirmfoto 2021-05-13 um 23 20 07" src="https://user-images.githubusercontent.com/12073163/118189190-c2dbf100-b441-11eb-919c-9c8654cf6773.png">

To get it to boot, I have to manually use the Boot Maintenance Manager to Boot From File: `/No Volume Label/EFI/kali/grubaa64.efi`.

**Comment by osy** [comment]
Should be implemented in https://github.com/utmapp/UTM/commit/d5600010064e3e7f0faf06e5632d167c9dea7519
