### ISSUE TITLE
"-append" qemu additional parameter space unescape support

### ISSUE THREAD

**Issue by drjerk1** [utmapp/UTM#266]
**Describe the bug**
QEMU has -append parameter, it passes one or multiple kernel boot parameters to kernel splitted with space, but utm also splits parameters on space so there is no way to specify multiple kernel boot parameters in additional qemu arguments utm section

ex.
-append root=/dev/vda ok.
-append rw ok
-append "root=/dev/vda rw" error.

**To Reproduce**
1. Add any linux arm64 kernel image to drives section (select type=kernel image)
2. Add -append "root=/dev/vda rw" to additional qemu parameters
3. UTM 0.9 will pass 3 arguments to qemu executable -append ; "root=/dev/vda ; rw"
4. Machine will not boot, no way to add rw kernel parameter to initrd

![9F596562-1B3C-47E1-B38E-BFFF858DD650](https://user-images.githubusercontent.com/12212715/79165142-2df46780-7deb-11ea-841b-4f848c0dd0ed.png)
![846E3982-B05E-418D-B454-69DDA3A61BFC](https://user-images.githubusercontent.com/12212715/79165159-351b7580-7deb-11ea-8d5f-3d9370903ce3.png)
![1C8F4E19-B9AA-40C9-AB43-6F9A99D1260B](https://user-images.githubusercontent.com/12212715/79165164-364ca280-7deb-11ea-8bcf-0505bc90e35d.jpeg)

**Comment by newperson1746** [comment]
I kept trying what the OP was doing and still failed... before I looked at the source code of the commit that fixed it and saw that the fix wasn't on the spaces handling, but on allowing double quotes to escape spaces selectively. I was trying for days before I realized that the fix was for the quotes. Maybe make it clearer in the release notes?

**Comment by osy86** [comment]
Sorry about that
