### ISSUE TITLE
Can we run VirtualHere in iOS UTM VM

### ISSUE THREAD

**Issue by JeongJaecheol** [utmapp/UTM#2672]
It would be great if the iOS UTM VM could run VirtualHere? For example, if you can run a VirtualHere server on an iPad Pro 5th generation to provide a USB4/thunderbolt4 port to a remote server, it would be very useful.

**Comment by conath** [comment]
That's a nice idea! Unfortunately (due to iOS sandboxing limits), UTM can only access USB devices on iOS if the iOS device is jailbroken. However you could absolutely install VirtualHere Server in a jailbroken UTM VM and pass a connected USB device over the network. Note that there is Thunderbolt passthrough is not available.
