### ISSUE TITLE
Mouse doesn't work on any Linux guest

### ISSUE THREAD

**Issue by rvdli** [utmapp/UTM#2693]
I'm running UTM on a M1 MacBook Air, already tried using Ubuntu, Debian and Fedora guests, but all of them have the same issue: I can't use the mouse at all.

I click anywhere on the screen, nothing happens. Sometimes I try to use the guest only with the keyboard, without even moving the mouse, and it starts "clicking" randomly in the corners of the screen, getting my windows out of focus and this kind of stuff.

How can I even start to trace the source of this issue?

**Comment by conath** [comment]
Please try the following: at the top of the VM window is a button with a little mouse pointer on it. It captures the mouse into the VM and is made for cases like yours where the guest OS doesn't support pointer "continuity" from the host.
<img width="340" alt="utm-capture-pointer" src="https://user-images.githubusercontent.com/12073163/128075374-01f46239-4c21-4a63-8af1-4466b077e88a.png">

Click it to capture the mouse, then try to use the guest OS normally with your host mouse and keyboard. (some macOS system shortcuts will not be passed to the VM)

If this works, the issue is not with UTM but rather with your guest not supporting pointer "continuity". You can use this as a workaround or you can try to install spice guest tools in the guest, if available for your distro. 

`sudo apt install spice-vdagent`
