### ISSUE TITLE
unable to install win10 64 bit: a media driver your computer needs is missing

### ISSUE THREAD

**Issue by simteraplications** [utmapp/UTM#2694]
Hi. I am successfully using windows10 arm with utm but i need an intel build due to an app i use needs .net framework 3.5 which does not seam to be available under arm windows, also i sometimes need a german environment because thats my main language. So i got my win10 iso (used the media creation tool on my hp notebook) and created a vm. I chose an intel processor with 4 cores, gave it 4gb ram and created a 256gb virtual drive with nvme and a removable cd drive for the iso. The vm booted as expected and i said start setup. While attempting to start the setup windows said that there is a media driver required for this pc which is missing. It's not showing me what it needs just that it needs something. I then made a second cd drive and put the spice guest tools iso in it and told windows to search there but it did not find what it was looking for so doesn't let me install. I am using a m1 macbook air 2020 with 8gb ram, 8 cpu cores and a 512 gb drive. Utm did not crash and the debug log only sais that it ran qemu, no emulation errors or any thing. Any one knows what windows problem might be and how to solve it?

**Comment by conath** [comment]
Hi @simteraplications. Thanks for your detailed message. I'll move this to Discussions since it's not a technical issue with UTM. 
While I can't answer your question, I can offer you an alternative, known good setup process for Intel Windows 10 on M1 Mac. [I have created a video tutorial on how to install it, covering the entire process step by step.](https://www.youtube.com/watch?v=KsNoGPczavw)
