### ISSUE TITLE
The startup installer doesn't start using my Mac mini m1?  It leaves with me a shell prompt

### ISSUE THREAD

**Issue by chadgarber** [utmapp/UTM#2723]
**Describe the issue**
The startup installer doesn't start using my Mac mini m1?  It leaves with me a shell prompt
**Configuration**
* UTM Version: 
* OS Version: 
* Intel or Apple Silicon? 

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open Console.app, go to `Crash Reports`, and find the latest entry for either QEMU, QEMUHelper, or qemu-\*. Right click and choose `Reveal in Finder`. Attach the report here.

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the top of the `QEMU` page is `Debug Log`. Turn it on and save the VM. After you experience the issue, open the VM settings again and select `Export Log...` and attach it here.

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by conath** [comment]
Please take a quick look at your issue, and you will see that we have provided a template for you to fill with the technical information needed. Please edit or comment on this issue with the information needed so we can support you. Thanks.

We will need a much more detailed description of the "startup installer", as well. For example, which operating system are you trying to install.

I am (temporarily) closing this issue due to missing information.
