### ISSUE TITLE
adattatore wifi alfa awus036nha

### ISSUE THREAD

**Issue by thegabrystudios** [utmapp/UTM#3022]
ciao. non riesco a collegare il mio adattatore wifi alla macchina virtuale di utm. Su utm ho installato kali linux. L'adattatore che sto usando è alfa atheros AWUS036NHA

Google translated:
> Hello. i can't connect my wifi adapter to utm virtual machine. On utm I have installed kali linux. The adapter I am using is alfa atheros AWUS036NHA

**Comment by conath** [comment]
Please provide the necessary information to we can support you. When you clicked on New Issue there was a bunch of text in the template for you to fill out:

**Describe the issue**
A clear and concise description of what the issue is. **BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Configuration**
* UTM Version: 
* OS Version: 
* Intel or Apple Silicon? 

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open Console.app, go to `Crash Reports`, and find the latest entry for either QEMU, QEMUHelper, or qemu-\*. Right click and choose `Reveal in Finder`. Attach the report here.

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the top of the `QEMU` page is `Debug Log`. Turn it on and save the VM. After you experience the issue, open the VM settings again and select `Export Log...` and attach it here.

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.


Please provide the information and reopen this issue. Thanks.
