### ISSUE TITLE
Improve Export Debug Log feature

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#3029]
The Debug Log feature is very helpful for diagnosing problems with UTM and guests. However it has two flaws: 

1. It is unclear what needs to be done to get a log, turning on the switch doesn't let the user know they have to start the VM again.

2. Clicking on the export button on macOS results in an iOS-like share sheet instead of a "Save as…" window like one might expect.

**Comment by ktprograms** [comment]
Should the debug logging be enabled by default? If the user can't remember what exactly happened to cause a crash, having the debug log available instead of having to try to reproduce it might be better?

**Comment by osy** [comment]
@ktprograms There is a slight performance hit when enabling debug logging. Also there's privacy concerns if someone else accesses the log or you share the VM without knowing about the log.

**Comment by ktprograms** [comment]
@osy I see.

I think I can work on fixing the export interface, but there's two problems:

1. The `exportDebugLog` function in `UTMData.swift` first copies the `debug.log` to a temporary url. Would it be possible to just return the URL to the actual debug log?
2. SwiftUI has a `.fileMover` modifier which is simpler to use than `NSSavePanel` + `FileManager` but it doesn't seem to count as a `User selected file`. I don't mind using the `NSSavePanel` stuff but if `.fileMover` can work it's neater. Example usage of `.fileMover`: `.fileMover(isPresented: $showing, file: URL(fileURLWithPath "/path/to/source/file")) { result in /* ignoring result but it always errors with: (source file) couldn’t be moved because you don’t have permission to access (destination folder) */ }`. I tested that this exact example works in non sandboxed apps.

**Comment by osy** [comment]
I think `fileExporter` is the right way but it requires a `FileDocument` which I was too lazy to implement. If you implement `FileDocument` then you don't have to copy the log to a temporary location.

**Comment by ktprograms** [comment]
The way I was thinking of implementing it is the `UTMData.exportDebugLog` function will return `[srcLogPath]`, then there will be a NSSavePanel (which doesn't actually save since you need to provide your own save code) that on a file chosen will use `fileManager.copyItem(at:to:)`.

**Comment by ktprograms** [comment]
For iOS, does `UIActivityViewController` do a copy or a move to the selected location?

**Comment by ktprograms** [comment]
For iOS, does `UIActivityViewController` copy the file or move it?
