### ISSUE TITLE
Add vga option (cirrus / std / vmware / qxl)

### ISSUE THREAD

**Issue by obbcth** [utmapp/UTM#303]

**Comment by osy86** [comment]
@obbcth Can you explain why? What will this add?

**Comment by obbcth** [comment]
Use cirrus in old windows (like 9x, 2000) doesn’t have to install vga drivers.
There is no essential reason to add this option, but with this we can choose more vga cards.

**Comment by osy86** [comment]
Moving this to post 1.0 because it would require adding new config option and it will take some thinking to not make it confusing for the user (i.e. if they don't select QXL and try to use SPICE tools and find that it doesn't work). Since it seems like you can install VGA drivers, this isn't high priority.

**Comment by conath** [comment]
FWIW you can go to VM settings -> QEMU and add the line `-vga cirrus` to the end to switch to cirrus graphics. It seems like the last -vga option in the list is the one used by QEMU. This isn't a solution though as it's not user friendly. Here's a [list of many QEMU graphics options](https://www.kraxel.org/blog/2019/09/display-devices-in-qemu/); note I don't think all of them are supported in UTM. 

![IMG_0056](https://user-images.githubusercontent.com/12073163/99879054-1a736f80-2c0a-11eb-85f7-a8898cc6c312.jpg)
![IMG_0058](https://user-images.githubusercontent.com/12073163/99879056-1ba49c80-2c0a-11eb-97c0-2517b14f1d75.jpg)
