### ISSUE TITLE
All network interfaces broken on v2.2.1 (Beta) (Ubuntu 20.04.3)

### ISSUE THREAD

**Issue by SuperOkazaki** [utmapp/UTM#3051]
**Describe the issue**
Using UTM v2.2.1 (Beta), a fresh installation of Ubuntu Server for ARM is not detecting any network interfaces. I am unable to try to manually change settings because the YAML files in `cd /etc/netplan` are empty and I cannot get any kind of Desktop Environment installed to troubleshoot with a GUI, since there is no network access for apt.

I have tried nearly every setting in the Network pane, including the new Bridged network mode. After going through several GitHub issues, it seems that `virtio-net-pci` and `rtl8139` are the correct emulated network card, but they also produce no results under any Network Mode.

Running `dig @1.1.1.1 [any url]` times out. 

**Configuration**
* UTM Version: v2.2.1 (Beta)
* OS Version: macOS Big Sur 11.5.2
* Apple Silicon

[debug.log](https://github.com/utmapp/UTM/files/7061759/debug.log)
[config.plist.zip](https://github.com/utmapp/UTM/files/7061760/config.plist.zip)

**Comment by SugarRayLua** [comment]
@SuperOkazaki ,

I’ve had trouble periodically with different UTM versions and VMs with internet access. What seems to work consistently when I have internet VM issues is to change the settings in the VM from DHCP to using the following static Internet address:

IP Address: 10.0.2.15
Netmask 24
Gateway 10.0.2.2
DNS 1.1.1.1

I’m a linux novice so not sure if this is the best or correct fix, but has consistently worked for me.

Fyi and good luck!

**Comment by SuperOkazaki** [comment]
@SugarRayLua are you changing these settings from within the VM, or are they set this way inside the UTM settings panel? I tired them in UTM settings to no avail, and I am unable to change them within Linux due to the absence of a network device that can be configured.

**Comment by SugarRayLua** [comment]
Hi, @SuperOkazaki, yes, when I have problems with internet connection, I change settings within the VM (I usually set up all my VMs with the same settings first outside the VM though with the “Network”, “Show Advanced Settings” in UTM and enter those settings that consistently work). In my Debian 10 x64 XFCE, going to “applications”, “settings”, “advanced network configuration”, “Ethernet”, and then “wired connections” and then changing the IPv4 settings to manual method with the settings listed above usually has done the trick. I’m now also using a Ubuntu 20 x64 build and the same method has previously worked in the past in Ubuntu (entering through “wired connection”, “web settings” and configuring the same settings). Unfortunately, I think I just jinxed myself with the advice I gave, I went into my Ubuntu VM this morning and its network connection stopped working, and I couldn’t get it back by the same method this time :-(. I had working last night at home on wifi and now switched to 5G wireless connection on my iPad Pro which might have somehow triggered the problem. I’ll let you know if I figure it out how to get the connection back—otherwise, perhaps someone else on this issue can help you (although my Ubuntu connection was working on v.2.2.1 just last night and didn’t change anything else—I’ve had the intermittent network connection loss seemingly at random times on multiple UTM versions and different VM builds. Good luck!

**Comment by SuperOkazaki** [comment]
@SugarRayLua Yeah, that's basically the crux of my issue-- I can get x86/64 VMs running and fully operational with internet  access (I've done it with XUbuntu and Debian), but any ARM virtual machines lack any kind of internet. If you find a solution please let me know because as of now, ARM Linux is unusable in UTM for me.

**Comment by SugarRayLua** [comment]
@SuperOkazaki —will do! I overlooked the detail that you were specifically asking about ARM. I’ll try after work setting up an ARM to test out (my only ARM VM now is on UTM SE). Not sure solely ARM issue though since my Ubuntu connection that went out this morning was x64. (IPad Pro host itself has 5 bar 5G connection).

**Comment by SugarRayLua** [comment]
@SuperOkazaki, on the positive side, when I went back into my Ubuntu x64 VM, the network was working again.

However, I do confirm your same issue with Arm64 VM: I downloaded UTM’s Debian XFCE Arm64, and it would not connect to the internet no matter if I changed the settings to what I mentioned in the VM, nor if I reset the network from within the VM nor if I shutdown the Arm64 VM and booted it up again to try it. That is a new problem for me although I haven’t been using Arm64 VMs with UTM. Note that my UTM SE V2.2.1 with the same VM from UTM Gallery (Debian XFCE Arm64) does still connect fine to the internet with the same settings.

Please let me know if there is anything else I can test or confirm more to help.

**Comment by SuperOkazaki** [comment]
Just as an update, UTM 2.2.2 does _not_ fix this issue. The issue persists as previously reported.

**Comment by SugarRayLua** [comment]
@SuperOkazaki, in the meantime, had you gone back to reinstalling an older UTM version that doesn’t have the problem with ARM VM connecting to the internet? I did that temporarily to get accelerated graphics working again in x64 VM. When I reinstalled the older UTM it just replaced the newer beta and seemed to keep all my data in the VM intact. Fyi, in case you hadn’t already done so.

**Comment by trbtm** [comment]
Did you check if the setting `Console Only` "fix" the network for you? I know it's not a fix but something I stumbled uppon, maybe the issue #3094 I created is related.

**Comment by toddbu** [comment]
@SuperOkazaki, it seems like a less than satisfying answer to say that this is an Ubuntu problem and it won't be fixed. I'm relatively new to UTM, and after spending many frustrating hours trying to figure out what question to even ask in Google, I finally gave up. Since I know other people who are trying to switch from VirtualBox on an x86 Mac to a new virtualization environment on M1, all that I could say at the time was that UTM is not ready for prime time. I'm feeling a bit better about the situation at the moment, but I wonder how many other people are experiencing the same problem and giving up on UTM for good

**Comment by donutschool** [comment]
@SuperOkazaki, @toddbu, iRather than continually editing the netplan config, you could use the 'match' keyword to match the interface MAC address, so in In /etc/netplan/00-installer-config.yaml:

```
network:
  ethernets:
    enp0s6:
      match:
        macaddress: 02:31:F9:4F:65:79
      dhcp4: true
  version: 2
```
(After finding the correct 6-byte MAC address from 'ip a' or the UTM network config) As I understand it, this means that netplan just uses enp0s06 as its internal identifier, but chooses the actual interface based on its MAC address.

There's a clue to what is going wrong in the startup log:
`[    0.790460] virtio_net virtio1 enp0s5: renamed from eth0`
...so UTM/QEMU are consistently calling the interface 'eth0' and it's something in the ubuntu startup deliberately 'standardising' the interface name to include its PCI bus and slot number, and the  ubuntu installer immortalises this in the netplan configuration.  Apparently, UTM sometimes changes the device order, which changes the name that ubuntu assigns to the interface. You'd probably get the same effect on a physical machine if you juggled the PCIe cards ... 

Keep Calm and Blame Systemd :-)

I think this is just a consequence of Ubuntu Server using NetPlan which is better for more complex server setups with multiple interfaces & users who like editing config files, c.f. Ubuntu Desktop using NetworkManager which is more plug'n'pray and user friendly (until you want to do something nonstandard!)  Ubuntu Server's default behaviour - tying the config to a card in a specific location - is probably what some people want.

All UTM can really do is flag the issue and, maybe, try and keep the order of devices as static as possible.

**Comment by osy** [comment]
I’ve decided to reorder the devices in v4.0 so network devices will always be first. That means this shouldn’t be an issue in the future as the first network device will always have pci slot id 1. Unfortunately this means that everyone’s network is going to break one time when they update to v4.0.

**Comment by yllekz** [comment]
Is this truly fixed? Wrestling with this issue in Kali Linux today. Seems to be a race condition because it didn't come up on one Mac while it did on another, both VMs with identical settings.
