### ISSUE TITLE
Setting "Use Command+Opt for input capture/release" does the opposite of what it says

### ISSUE THREAD

**Issue by jaigak** [utmapp/UTM#3176]
**Describe the issue**
By default, Use Command+Opt for input capture/release seems to be not checked however it's enabled but when checking it, it disables Command+Opt for input capture/release.

**Configuration**
* UTM Version: 2.3.0 (37)
* Intel or Apple Silicon? Apple Silicon

**Comment by osy** [comment]
And does Ctrl+Opt work when it’s checked and not work when it’s not checked?

**Comment by Jaiganeshkumaran** [comment]
Sorry, I read the option incorrectly. When checked Cmd+Opt works but Ctrl+Opt doesn't work. I think it should be named "Use Command+Opt for input capture/release instead of Ctrl+Opt for clarity".

**Comment by osy** [comment]
So the intention is that if you press the Capture Mouse button, then it shows you in the title bar the key to release. And if you press it again it captures.

The setting is there to toggle an alternative button (as well as for VoiceOver users since Ctrl+Opt is used for VoiceOver). I don’t think writing down what an option doesn’t do (instead of …) is more clear.
