### ISSUE TITLE
On iOS 15, iPad Pro M1 (8GB RAM) can't allocate 4 GB of RAM for the VM

### ISSUE THREAD

**Issue by Andymulator** [utmapp/UTM#3193]

**Comment by conath** [comment]
UTM needs more than the RAM you assign to the VM. The total RAM usage is about 1.5x what you request, partially due to how UTM works and partially due to iOS limitations. So if you request 4 GB in the config, it will use close to 6.5 GB (500mb for UTM app itself) which is probably too much. 3.5 GB should work (3.584 MB).

**Comment by conath** [comment]
No need to be sorry for asking a question. :)

I've reached out to osy86 so we should soon know for sure.

**Comment by conath** [comment]
Follow the instructions in [iOS Development](https://github.com/utmapp/UTM/blob/master/Documentation/iOSDevelopment.md)
