### ISSUE TITLE
LICENSE file and webpage out of date

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#3235]
The LICENSE file is outdated, and the [License](https://mac.getutm.app/licenses/) webpage should include the license for the [ZIP Foundation](https://github.com/weichsel/ZIPFoundation) library that was recently added.

**Comment by osy** [comment]
I updated the readme file to link to all the MIT licensed Swift packages we use to be a good citizen. The License webpage is there for GPL because the copy-left license requires that we re-distribute the packages upon request and provide the changes and build instructions. AFAIK, MIT and other permissive licenses do not have such a requirement.
