### ISSUE TITLE
USB Passthrough to VM Not Working

### ISSUE THREAD

**Issue by MDNich** [utmapp/UTM#3322]
USB Devices configured to be connected to the VM are not connected to the vm.

**Configuration**
* UTM Version: Version 2.4.1 (40)
* OS Version: 12.0.1
* Intel or Apple Silicon? M1 iMac Yellow

**Crash log**
No crash. Just bad behavior

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/7567673/debug.log)
Looked through, nothing on USB errs.

**Upload VM**
Ooh. A little big. Not happening

**Comment by ktprograms** [comment]
> **Upload VM**
> Ooh. A little big. Not happening

Then uploading the `config.plist` file inside the `.utm` VM package will be the next best.

**Comment by conath** [comment]
From the Debug Log I can deduce your VM is configured as follows:

- System Mac99
- USB 3 Support enabled in VM Config => Sharing

This is definitely not compatible, as the old PowerMac system don't support USB 3. 

At first I thought USB sharing might work if you disable USB 3 Support:
![disable-usb3-sharing](https://user-images.githubusercontent.com/12073163/143311837-19e2620e-f596-49f4-ac71-f3bf8e5a8690.jpg)

However, after testing this myself with a Mac99 VM running MacOS 9, I have discovered the USB 2.0 sharing is also not compatible. Unfortunately, we can't fix this because our backend technology only supports USB 2.0 as the oldest option for passthrough/sharing.

**Comment by MDNich** [comment]
Wait but my OS is Leopard not Mac OS 9. Thus it might work. Is there a switch to set USB mode?

**Comment by conath** [comment]
See screenshot in my above reply; the switch to change to USB 2 is in the VM config => Sharing.

**Comment by MDNich** [comment]
Maybe if only USB 2.0 was enabled it might work

**Comment by conath** [comment]
If you uncheck the "USB 3.0 sharing" box it means USB sharing remains on, and switches to USB 2 mode. I can see how this UI is confusing.

**Comment by MDNich** [comment]
Hmmm. There is no 1.0 I suppose?

**Comment by MDNich** [comment]
So basically you are saying that there is no USB support for mac99 vms

**Comment by conath** [comment]
There is no USB passthrough support for mac99. As I wrote above:

> However, after testing this myself with a Mac99 VM running MacOS 9, I have discovered the USB 2.0 sharing is also not compatible. Unfortunately, we can't fix this because our backend technology only supports USB 2.0 as the oldest option for passthrough/sharing.

You can use simulated USB 1 devices like a USB floppy or CD drive, and usb mouse and keyboard. But not pass through real ones.

**Comment by MDNich** [comment]
That is a real bummer. Any other ppc machine (VM) with usb passthrough?

**Comment by conath** [comment]
I don't know. Depends if any PPC VMs will be able to use the ICH9 USB bus provided by the backend, QEMU. 

Did you try the passthrough again with USB 3 support unchecked?

**Comment by MDNich** [comment]
Yes I tried with both configs unfortunately
