### ISSUE TITLE
When installing Ubuntu 20 Server-amd64, the following crash occurs

### ISSUE THREAD

**Issue by adagioNeo** [utmapp/UTM#3356]
_[technical information missing entirely – conath]_

<img width="1512" alt="Screenshot 2021-11-30 at 12 58 44 PM" src="https://user-images.githubusercontent.com/65425092/144100862-1f3285b3-7e2d-4e74-a024-51661f051460.png">

**Comment by conath** [comment]
It seems like you are attempting to install Ubuntu 20.04 Sever 64-bit while using a guest VM configured with the pc-1996 system. Please try changing to q35-2009 system, and make sure the EFI boot check box is selected (in the System tab → Show advanced).

Due to missing technical information outlined in the issue template, I am closing this issue. If you would like to follow up on the problem you encountered or a different problem, please create a new issue with the required information.
