### ISSUE TITLE
Publish latest update to homebrew-cask automatically

### ISSUE THREAD

**Issue by hannesa2** [utmapp/UTM#3389]
Hi, you have a very nice github action pipeline and I see UTM on brew too

<img width="556" alt="image" src="https://user-images.githubusercontent.com/3314607/146316756-1a57404a-9b27-4b04-9eb6-ed2945e5249e.png">

Do you publish this automatically (and where) or how do you do this ?

Thank you

**Comment by JacksonChen666** [comment]
it's within [homebrew cask](https://github.com/Homebrew/homebrew-cask)

there's likely no auto publishing process, but updates to the cask repo can be made by anyone with `brew bump-cask-pr` easily

**Comment by conath** [comment]
TIL UTM is available via homebrew - makes sense, though. Looking at [the latest commit referencing UTM](https://github.com/Homebrew/homebrew-cask/pull/113941), it seems like the updates are indeed submitted via `brew bump-cask-pr`.

I'll leave this open because UTM maintainers should ideally be submitting updates to `homebrew-cask` as soon as they are released. Maybe we can work out an automated process.

**Comment by JacksonChen666** [comment]
`brew bump-cask-pr` accepts arguments (`--url`, `--sha256`, `--version`, any must be specified), but the process *could* be automated.
but it does rely on the github api because the command creates a fork of the cask repo, push changes, creates a pr, and opens the pr in the web browser without user intervention(!) in case of success. so the command itself is automated.
the command also errors out if there's already a pr for an update. definitely don't want to have more than 1 pr for the exact same thing.

here's [all utm updates with the command](https://github.com/Homebrew/homebrew-cask/issues?q=label%3Abump-cask-pr+utm). i found no one who could be affiliated with this software project itself.

personally, it's just more hassle to setup automation for the automation when the community itself is allowed to update. someone can simply subscribe for releases on this project and run the command when they receive a notification. or the utm maintainers themselves could do it, if they wish.
