### ISSUE TITLE
Parallels and Snow Leopard

### ISSUE THREAD

**Issue by SonikArchitects** [utmapp/UTM#3404]
Hi there,

I have 2 questions. One is : does anyone have instructions on translating a working Intel Parallels VM? Question two is does anyone have a Leopard or Snow Leopard template?

Thanks!

**Comment by mavethee** [comment]
1. it's not a place for Parallels and even tho, there is no ARM Snow/Leopard release so that won't work anyway.
2. Template for OSX on PPC is not really needed all you have to do is switch arch to PowerPC, set 1 core, 2048 ram is a max, display as VGA (other won't work, you will see blank screen) and your DVD for Leopard. For install DVD image must be first in boot order, after install it will want to reboot eventually will fail to force reboot to hard drive so don't worry just press reboot and as soon as you see OpenBIOS screen, close VM, set boot order for HDD first.
If Network doesn't work (#3399) just try adding this line in QEMU tab in settings (scroll down, paste and press enter then save):
```-device sungem,netdev=network01,mac=52:54:00:12:34:56 -netdev user,id=network01```
