### ISSUE TITLE
Swift Playground integration?

### ISSUE THREAD

**Issue by t0kvgh** [utmapp/UTM#3407]
Since release of Swift Playground 4 which includes debugging capabilities, would it be possible to launch Swift Playground from there and still use JIT?

Also, Swift Playground support subscription via url which make update easier.

**Comment by conath** [comment]
I believe you meant to write,

> would it be possible to launch *UTM* from there and still use JIT?

So you are asking, could Swift Playgrounds 4 be used to start UTM? I don't know for sure, but I believe no.

There are two ways to launch a JIT enabled app. Either you are building and running the code, using Xcode. Or you have already installed the app and are attaching a debugger to it.

Regarding the first way: you can't build and run UTM from Swift Playgrounds because the project is much too complex for its build system. I am not sure if it would be possible to change UTM project to work in Swift Playgrounds – for now I would say it is an unrealistic amount of effort.

Regarding the second way: You can already launch UTM with AltStore or from an iOS Device using [Jitterbug](https://github.com/osy/Jitterbug), even from the same device if you have a paid developer account. Since Swift Playgrounds is limited in functionality compared to Xcode, you can not debug a process that is already running (AFAIK there is no manual interaction with the debugger at all, including no breakpoints), so you wouldn't be able to enable JIT for separately installed UTM.
