### ISSUE TITLE
Need to press Caps lock key twice to register in the guest

### ISSUE THREAD

**Issue by mavethee** [utmapp/UTM#3415]
**Describe the issue**
I've noticed that there is an annoying input lag/bug that affects switching between upper and lower case letters (and vice versa) but it's only present in UTM (QEMU installed from brew and ran the same VMs doesn't experience that issue). You need to press Caps Lock twice to trigger action which is a bit annoying.

**Configuration**
* UTM Version: 2.4.1
* OS Version: 12.0.1 Monterey
* Intel or Apple Silicon? M1 MacBook Air

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/7780069/debug.log)

**Upload VM**
[config.plist.zip](https://github.com/utmapp/UTM/files/7780073/config.plist.zip)

**Comment by conath** [comment]
I can reproduce this on my machine:

- UTM Version: 2.4.1
- OS Version: 12.1 Monterey
- Intel or Apple Silicon? M1 MacBook Pro

**Comment by bradsevy** [comment]
I'm also experiencing this bug.

- UTM 2.4.1
- macOS 12.1
- M1 MacBook Air
- Behavior persists across multiple guest OSs; Ubuntu, Debian, and Arch

**Comment by snjoer** [comment]
Same bug here
* UTM 3.0.4
* MacOS 11.5.2
* Ma MacBook Pro

**Comment by osy** [comment]
This is a tricky one because the Caps lock state is handled by the guest OS. If you send the caps lock key before the OS has booted up (for example when the VM is started), it may not be visible.

However, one thing that can be fixed is capturing the Caps lock state while UTM is in the background. For that, a fix will be made.

The caps lock state can also be sent whenever the mouse is captured, but this will still fail if you capture the mouse before the guest OS has booted up. So the best way to ensure the caps lock is synchronized correctly (in the next update) is to capture the mouse at the login screen.

**Comment by Banedos** [comment]
I don't mean to bring up an old issue but I didn't see a clear solution to this.

After spending some time looking into this issue, I found the solution:

**Solution: Go to security & privacy in your Mac OS. Then for "Input monitoring" and "accessibility", add UTM for both.**
