### ISSUE TITLE
Add downloaded/total to VM download bar

### ISSUE THREAD

**Issue by mygizli04** [utmapp/UTM#3437]
In the v3.0.0 beta it is not obvious when the download will be complete, how much will be downloaded or how much has already been downloaded. I think adding a downloaded/total would help approximate how long it will take, along with displaying how much will approximately be downloaded before the download is started. Especially since it is not obvious when the progress bar ends.

![image](https://user-images.githubusercontent.com/42012824/147872840-a7b9f2a5-477e-4e11-b76b-d306073885b4.png)

**Comment by conath** [comment]
This looks like a layout bug. The progress bar is supposed to fill from left to right as the download progresses.

**Comment by mygizli04** [comment]
Yes, the picture attached is a layout bug but my request is still that a downloaded/total counter (like 1.0/12GB ) gets added even when the bug gets fixed ( maybe along with a grey bar behind the loading bar to make it obvious where the end is ) to be able to better tell how much is downloaded/going to be downloaded.

**Comment by conath** [comment]
That makes sense. I would prefer to keep the sidebar minimal and add this and other technical info to a detail view as suggested in #3432 . What do you think?
Though it might be nice to show an estimated time remaining in the sidebar.

**Comment by mygizli04** [comment]
It makes sense to me too. I'd love to see approximate remaining time, and current/total disk usage space in the details pane as mentioned in the issue you linked, along with showing how much data will be downloaded _before_ it starts.

<img width="452" alt="Screen Shot 2022-01-05 at 16 32 33" src="https://user-images.githubusercontent.com/42012824/148218937-17e94fb2-da55-4957-8963-80d26b103575.png">

**Comment by conath** [comment]
Turns out, getting a rough estimated time remaining is as simple as taking the elapsed time divided by the percent complete and subtracting the elapsed time from that. Then I [*just*](https://www.reddit.com/r/restofthefuckingowl) had to implement the rest of the UI and so we get the first piece of #3455.

![UTM-pending-vm-ETA](https://user-images.githubusercontent.com/12073163/148619777-52ac101a-0e2b-4841-bebd-7ee99f103115.jpg)

**Comment by conath** [comment]
@mygizli04 Would you be satisfied with the information shown in this screenshot?

![UTM-pending-vm-details](https://user-images.githubusercontent.com/12073163/148664500-efb78a7b-8347-4458-8a6b-884ced219561.jpg)

"Total Download Size" means the size of the file that is being downloaded (meaning this number does not change during the download).

**Comment by mygizli04** [comment]
Yes, I think that looks great. Is there a way to see how much has already been downloaded so far apart from the progress bar? Even without that I think it's much better than before.

**Comment by conath** [comment]
I've taken inspiration from Safari's download popover and come up with this:
![UTM-pending-vm-downloading](https://user-images.githubusercontent.com/12073163/148686199-113bb661-bb23-4654-8e28-9e0b94605473.jpg)
![UTM-pending-vm-extracting](https://user-images.githubusercontent.com/12073163/148686200-ba5d8abf-cc7c-49da-881e-f4b4483277f4.jpg)

I realize there is less padding on the side of the text than the top & bottom of the view but this way it is less likely to truncate (5MB…).

And here is what it looks like when downloading a macOS 12 VM from Apple:

![UTM-pending-vm-macOS-12](https://user-images.githubusercontent.com/12073163/148686348-d161084b-4a3b-40e0-ac6d-3ebf110ee8c1.jpg)

**Comment by conath** [comment]
I realized (as pointed out in the issue description) it's not obvious where the progress bar ends since it doesn't have a background color for the empty part. I fixed that, here is the new look:
![dark mode 1](https://user-images.githubusercontent.com/12073163/148687218-998acfd4-4e52-485f-9c9f-8565059576b9.jpg)
![dark mode 2](https://user-images.githubusercontent.com/12073163/148687221-890c30a6-6314-402e-ac7a-e7fb32705749.jpg)
![light mode 1](https://user-images.githubusercontent.com/12073163/148687223-88e95e85-7c17-4c3d-bfcf-d9f4914715ac.jpg)
![light mode 2](https://user-images.githubusercontent.com/12073163/148687224-d09ad886-d30f-40d8-a844-ce317039a414.jpg)

**Comment by brunocastello** [comment]
Can I suggest to make it a bit smaller, by moving the button to cancel at the end of the progress bar? I have a feeling that it would be better for the user. So he can cancel more than one machine downloads quickly, instead of hovering each one, for example. It's just one of the scenarios possible for that. Then the popup will be merely informative, rather than having to hover for an action... Just dropping my 2 cents

**Comment by conath** [comment]
@brunocastello I‘m not sure I understand what you mean by this:

> Can I suggest to make it a bit smaller, by moving the button to cancel at the end of the progress bar?

Regarding this:

> cancel more than one machine downloads quickly, instead of hovering each one, for example.

While this is not a use case I covered with this UI, I don’t believe this is a common use case at all. There is a workaround: The cancel button appears immediately on hover so you should be able to cancel the last one in the list, and then without moving the cursor keep clicking to cancel the other ones. 

The cancel button in the popover is an additional affordance to allow users to cancel if they did not notice the x button while hovering.

**Comment by brunocastello** [comment]
The button to appear on hover next to the progress bar is a good solution, I agree, it's even applied to some stuff like Finder sidebar, for example, so it's consistent UI overall. I'd have to be a rounded button with an icon and no text - macOS users know that a rounded button with a X is simply cancel, just like the one inside the popover on Safari. iOS has a single blue X next to it. Again, consistency.

But another one inside the popover is simply redundance. OK, I know it's simply personal opinion, but the more I look at it, the more I think something is wrong and that it's redundant. Try with the above solution first, and then later if a really good number of users report that they fail to notice or use it, then proceed to add the additional button (but I am confident that it won't be needed, based on UI consistency and macOS users being already used to the UI for years).

It's just the design of the button inside the popover that is not correct IMO. For macOS UI consistency, the buttons inside popovers and modals can be either grey (Cancel) or Blue (OK). I don't recall having seen a big red one. You can improve it by using a rounded one with a X icon inside, no text, aligned to the right of the text with speed and image size, so at least it is consistent UI. Right?

**Comment by conath** [comment]
On iOS we use the swipe-to-delete interaction to cancel the download. 

The cancel button in the popup is red because it is a destructive action. You could potentially lose anywhere from minutes to hours of download progress if you click it by accident, depending on the network speed (I didn’t implement resuming a cancelled download - unlike Safari, the partial file is deleted immediately when cancel is clicked).

I’m not a fan of placing another (x) Button in the popover since the point of the popover is to offer more information and a more obvious way to cancel. So while I see what you are saying with regards to the redundancy, I disagree that it needs to be changed.

What I take away from this discussion is that my UI is not a great solution and needs to be redesigned. I am already not a fan of the pending VMs sitting in the list with the other VMs at the bottom - it’s not discoverable enough and the space is not sufficient to show all information. So I welcome your suggestions for a redesign, and I invite you to open a new issue if you have ideas for it.

**Comment by brunocastello** [comment]
Since you're saying that you're not a fan of the pending VMs sitting in the list... me too, but I think that the best solution would be to mirror exactly what Safari does. I don't remember if there are other apps with other solutions for downloading their content, but I'd like to hear and see what they do if there's any.

OK, so... where the downloads of VMs being downloaded could be moved to? Analyzing the macOS UTM UI, It could be the same place as safari, a download icon near the top right on the top bar of the window, and thus mirroring Safari's behavior, and when the download is completed, the newly-downloaded VM would appear on the sidebar, ready to use. Safari does show the overall progress with a small bar below their download icon, until you click on it to show the popover with the details for each download you're doing and 2 buttons to show in finder and cancel the download.

https://developer.apple.com/design/human-interface-guidelines/macos/indicators/progress-indicators/

Users would instantly recognize that download icon and what it is, since it mirrors the same thing and behavior as seen on Safari and they're used to it. With this method, the lack of space to show the information is not an issue anymore.

Following your invite to do it, I can happily come up with some art demonstrating how it would look like, but for the next days I have to design other big things first for my current work, and go out to try and get my third vaccine shot tomorrow. I'll let you know when I have something and open a new issue for that. However, I don't think that this is needed while we all know how Safari does it.
