### ISSUE TITLE
No more networking on Ubuntu/Debian after UTM upgrade 2.4.1->3.0.4

### ISSUE THREAD

**Issue by GregOriol** [utmapp/UTM#3532]
After an upgrade of UTM on macOS (12.1 on M1 mac) from v2.4.1 to v3.0.4, my existing Ubuntu 20.04 VMs (both x86 and arm64 ones) don't see any network anymore.

I didn't see anything about networking to change in the release notes.
On the arm one, it is set to a shared `virtio-net-pci`.
On the x86 one, it is set to a shared `e1000`.

Starting the same VMs with UTM 2.4.1 again works with networking OK.

Does anyone have any idea what to look for?

Here are files for the x86 one:
[config.plist.txt](https://github.com/utmapp/UTM/files/7925753/config.plist.txt)
[debug.log](https://github.com/utmapp/UTM/files/7925779/debug.log)

**Comment by tadpol** [comment]
I am seeing this as well.  Seems to only be with old VMs.  If I create a new VM the networking works.

**Comment by osy** [comment]
Can you follow the troubleshooting at https://mac.getutm.app/gallery/ubuntu-20-04

**Comment by tadpol** [comment]
I'm using Debian instead of Ubuntu, but following the basic ideas from "Networking is unavailable…"

Looking at `/etc/network/interfaces` and `ip link show` I see that the devices are different. (`ens10` instead of `ens9`).

Edited `/etc/network/interfaces` for the new device name and rebooted.  Networking is now working as expected on 3.0.4 for me.

**Comment by GregOriol** [comment]
@osy Thanks, that works! Is there a way to update the docs on that page to add that it can happen after the upgrade to 3.x?

**Comment by osy** [comment]
Yeah I'll make an update.
