### ISSUE TITLE
CD/DVD and Floppy forwarding 

### ISSUE THREAD

**Issue by upintheairsheep** [utmapp/UTM#3553]
Please browse the existing issues and filter by 'enhancement' to make sure this has not already been suggested!

Parallels has the functionality to forward a cd drive and you should too, however, some MacBook Pro 2012 can use it.

**Comment by osy** [comment]
This is not possible currently in an App Sandbox app. Note that Parallels’ App Store version doesn’t support this either.

**Comment by adespoton** [comment]
qemu can do this by itself as long as you're outside the sandbox.  But because UTM is intentionally designed as a sandboxed app, it won't have this ability.

Having said that, there might be a way to create a hard or soft link inside a sandboxed folder to a specific /dev/ device -- but this can't be done programmatically by UTM; you'd have to do this yourself after installation to get around Apple's security restrictions.

**Comment by conath** [comment]
Should this be closed as “wont fix”? 

A related thought: is it possible to pass bin/cue CD images to the VM? This format includes CD Audio which may be required for some older games.

**Comment by adespoton** [comment]
Probably should be; bin/cue and CSO/CHD support would be nice, but that would involve adding more third party code based outside QEMU and SPICE.

cebix macemu has the bin/cue code we'd probably want here.
