### ISSUE TITLE
QEMU custom arguments cannot contain spaces.

### ISSUE THREAD

**Issue by adespoton** [utmapp/UTM#3579]
**Describe the issue**
When putting paths or parameters into a QEMU argument, UTM's parser appears to use spaces as breaks, no matter whether the string is single or double quoted or the spaces are escaped.
So "path/to this/file.qcow2", 'path/to this/file.qcow2' and path/to\ this/file.qcow2 all break.

While drive paths can be handled by removing the actual spaces in file names and directory names, setting a device label to a product string containing spaces is a bigger issue, such as:

-device scsi-cd,scsi-id=3,drive=cd1,vendor="MATSHITA",product="CD-ROM CR-8005",ver="1.0k"

UTM will split this at CD-ROM, which results in an error when you attempt to run the VM.  Of course, the hardware in question won't recognize the CD-ROM drive without this label, so it can't just be modified to remove the space.

**Configuration**
* UTM Version: 2.x and 3.x up to 3.0.4
* OS Version: macOS 12.2
* Apple Silicon

**Comment by osy** [comment]
We currently support quotes at the start and end of an argument but not in middle of one https://github.com/utmapp/UTM/blob/master/Managers/UTMQemuSystem.m#L703

**Comment by adespoton** [comment]
Wouldn't it make more sense to split at \S\- instead of at \S?  QEMU requires argument markers for all arguments.

**Comment by NothinRandom** [comment]
Hello.  I am facing a similar problem when setting DMI info


**Describe the issue**  
From QEMU man page https://www.qemu.org/docs/master/system/qemu-manpage.html, it is possible to have spaces in the DMI info for fields using single quote to wrap keys that have spaces.  For example,

`-smbios type=1,manufacturer='Custom builder',product='Custom product'`

However, UTM is throwing error
```
QEMU error: QEMU exited from an error: qemu-x86_64-softmmu: builder',product='Custom: Could not open 'builder',product='Custom': No such file or directory
```

If a delimiting char such as _ or - is used to separate, then UTM can start VM and works fine but of course does not provide valid DMI info.

Also tried 
`-smbios type=1,manufacturer="Custom builder",product="Custom product"`.  While this works and UTM can start, the DMI info is altered from `Custom builder` to `"Custom builder"` (i.e. name now is wrapped in double quotes, which is invalid).

**Configuration**  
* UTM Version: 4.7.4
* macOS Version: 15.7.1
* Mac Chip (Intel, M1, ...): M1

Let me know if I should open new issue instead of commenting here.  Thanks!

**Comment by osy** [comment]
Use double quotes

**Comment by NothinRandom** [comment]
@osy I tried a few different combinations.

1. The following produces error message `1213:1227: syntax error: Expected “,” or “}” but found identifier. (-2741)`  
`set config_config to config_config & {qemu additional arguments:{argument string:"-smbios type=1,manufacturer="Custom Builder",product="Custom Product"}}`
    1. This is with/without space and is coming from applescript.  What should the correct syntax be?

1. If I update so that content is escaped with double quotes
`set config_config to config_config & {qemu additional arguments:{argument string:"-smbios type=1,manufacturer=\"Custom Builder\",product=\"Custom Product\""}}`
   1. This allows me to start VM.  However, when I run `dmidecode -s system-manufacturer`, I'm getting `"Custom Builder"` instead of just `Custom Builder`

3. If I update so that content is escaped with single quotes
`set config_config to config_config & {qemu additional arguments:{argument string:"-smbios type=1,manufacturer='Custom Builder',product='Custom Product'"}}`
   1. AppleScript doesn't throw error, but UTM throws the error mentioned previously `QEMU error: QEMU exited from an error: qemu-x86_64-softmmu: Builder',product='Custom: Could not open 'Builder',product='Custom': No such file or directory`

**Comment by NothinRandom** [comment]
If I manually go into settings and go into QEMU > Arguments and add new entry `-smbios type=1,manufacturer="Custom Builder",product="Custom Product"`, then this results in the same output as #2, where dmidecode yields `"Custom Product"` instead of just `Custom Product`
