### ISSUE TITLE
Bridge Networking Support

### ISSUE THREAD

**Issue by semaja2** [utmapp/UTM#358]
Is there plans to add bridged host networking support? Or is this a restriction from the iOS platform

I have some applications that work on layer 2 technologies that won’t work behind the current NAT design

**Comment by osy86** [comment]
Not sure if it’s possible.

**Comment by professorIsaac** [comment]
This would be useful for a virtual machines running altserver.

**Comment by geoff-nixon** [comment]
> Not sure if it’s possible.

It's possible.

https://www.amazon.com/Ethernet-Adapter-iPhone-Power-Charge/dp/B07FKQS5NB
https://www.tetherme.net/faq

**Comment by osy** [comment]
Reopening due to apple bug.

**Comment by bearnol** [comment]
Does the bridged-networking recently added (thanks!) to Mac UTM work with IPv4-only address(s)? I’m trying to run a really old Fedora16 (2011 vintage) i386 VM that knows nothing of IPv6, and so far without achieving network access. For routing purposes the IP address of the VM must be just 192.168.0.205. (When I run ifconfig inside the VM, I think I see only IPv6-type interface(s) listed?? Also, pinging external addresses doesn’t work, and the Fedora networking icon in the status bar at the top lists “No network connection” currently)
[btw, I was impressed with how easily UTM imported and converted the HDD image from original old VirtualBox to qcow2 - cool!].
I’m very new to UTM, having just bought my first M1 Mac mini :), so it may well just be something I haven’t seen yet… ( it took me a little while to work out I had to turn off UEFI on the virtual HDD to get it to boot)
[also btw, emulation speed seems fairly impressive, possibly fast enough for me to use in production, thx again, tho I guess that’s to be hoped/expected with QEMU underneath]
J

**Comment by ap46281** [comment]
Has anyone got bridge networking on iOS? Been a few months since this was last mentioned and I am not following how to make this work.

**Comment by osy** [comment]
Sorry bridged networking is a macos only feature. This issue was filed before the macos version was finished so it refers to iOS.

**Comment by bearnol** [comment]
> Does the bridged-networking recently added (thanks!) to Mac UTM work with IPv4-only address(s)? I’m trying to run a really old Fedora16 (2011 vintage) i386 VM that knows nothing of IPv6, and so far without achieving network access. For routing purposes the IP address of the VM must be just 192.168.0.205. (When I run ifconfig inside the VM, I think I see only IPv6-type interface(s) listed?? Also, pinging external addresses doesn’t work, and the Fedora networking icon in the status bar at the top lists “No network connection” currently)
> [btw, I was impressed with how easily UTM imported and converted the HDD image from original old VirtualBox to qcow2 - cool!].
> I’m very new to UTM, having just bought my first M1 Mac mini :), so it may well just be something I haven’t seen yet… ( it took me a little while to work out I had to turn off UEFI on the virtual HDD to get it to boot)
> [also btw, emulation speed seems fairly impressive, possibly fast enough for me to use in production, thx again, tho I guess that’s to be hoped/expected with QEMU underneath]
> J

(Replying to my own post :) hope that’s ok)
I found the following page, which may well be helpful - I haven’t tried it yet, but it looks very promising given the exact diagnostics that I saw…
https://boinc.berkeley.edu/trac/wiki/VmServer
ie one needs to change something inside the VM, because of the implicit HD clone and therefore hardware change.
[PS I’ve now also literally just bought my _second_ M1 Mac mini - they’re great!]

**Comment by ap46281** [comment]
> Sorry bridged networking is a macos only feature. This issue was filed before the macos version was finished so it refers to iOS.

Is this a viable feature in the future? Or more of a dream?

**Comment by SuperKenVery** [comment]
I ran into the same issue, no IPv4, only IPv6. Any ideas?

**Comment by bearnol** [comment]
Hi,
Thanks for your email.
Unfortunately I don’t have a definitive answer for you, and in fact shortly after I wrote my first post re ipv4 vs ipv6 I paused investigating the issue.
I did later wonder if the problems I was having were actually due to an implicit cloning of my VM, and therefore that the network config file needed tweaking (rather than the problem you/we mention), but I have not checked/confirmed this.
Either way good luck with it - if you do get it working pls could you advise me too! :)
James (Wanless)

**Comment by SuperKenVery** [comment]
I didn't clone my vm and I tried to tweak my network configuration, with no luck. 

https://bugzilla.redhat.com/show_bug.cgi?id=1832723

This seems related but does not solve my problem. My firewall on macOS is off.

**Comment by bearnol** [comment]
Thanks for extra info…
J

**Comment by bearnol** [comment]
Bit of hopefully good news on this:
I think I’ve been able to workaround quite nicely simply by selecting “Emulated VLAN” rather than bridged networking as such, and then port-forwarding port 80 from in/outside the VM, to allow the web server inside the VM to become visible to the outside world on the IP of the host.
HTH,
J

**Comment by ThijmenDam** [comment]
@bearnol great solution!
