### ISSUE TITLE
Prebuilt Debian ARM VM shows only blinking cursor

### ISSUE THREAD

**Issue by iArti** [utmapp/UTM#365]
I have downloaded Debian ARM Xfce VM on my iPad. It showed up GRUB, then "Guest disabled display." and after, it stuck with just blinking cursor, with no ability to input anything. I tried to wait for around 10 minutes, however, nothing changed. How to make it work?
I'm using latest version (1.0-rc4) on iPad Air 2 running iPadOS 13.5

**Comment by Rick1029** [comment]
When I boot up Debian I also get the guest disabled display, followed by the blinking cursor. After about 30 seconds it disappears and I go into the login screen. Are you sure you didn’t disable or remove lightdm or xfce? Make sure you have enough cores and ram allocated, because the base install works fine for me (4 cores and 1 gig of ram)

**Comment by iArti** [comment]
> When I boot up Debian I also get the guest disabled display, followed by the blinking cursor. After about 30 seconds it disappears and I go into the login screen. Are you sure you didn’t disable or remove lightdm or xfce? Make sure you have enough cores and ram allocated, because the base install works fine for me (4 cores and 1 gig of ram)

I didn't change anything in the settings apart from reduce core count to 3 (because Air 2 has 3 cores) and RAM to 768Mb
I think both is okay for Xfce

**Comment by osy86** [comment]
I don’t know how slow it is on older devices. Try waiting an hour.

**Comment by osy86** [comment]
You probably need to decrease the core count since iPad Air 2 has 3 cores.
