### ISSUE TITLE
QEMULauncher takes up 100% CPU

### ISSUE THREAD

**Issue by eranroll** [utmapp/UTM#3684]
Hi,

I am using UTM on my Mac to run Ubuntu 21.10

My Mac is a 2019 Intel i9 MacBook Pro, 1TB, 32GB Ram. I would expect that QEMU won't even run, since there is no emulation required, however it still runs and takes up almost all of my cpu.

Is there a way to work around it? Perhaps some wrong config?

Thanks!

**Comment by osy** [comment]
This is expected because the way macOS sees a CPU as idle (not in use) is when it is executing the idle thread in the kernel. However, when you're running a VM, the CPU is never "idle" but instead executing the "idle" thread in the guest OS. Some more advanced VM software allows the host and guest operating system to work together to decide if it's idle or not.
