### ISSUE TITLE
Cannot use Split View or Slide Over with the app installed from AltStore

### ISSUE THREAD

**Issue by kkk669** [utmapp/UTM#369]
**Describe the bug**
UTM 1.0-rc5 supports Split View, but I can't use Split View when I installed from the AltStore.

![IMB_RN8rA3](https://user-images.githubusercontent.com/601636/83968644-9ea89380-a905-11ea-82bd-2a712e557794.gif)
![IMB_OiLRBz](https://user-images.githubusercontent.com/601636/83968650-a7996500-a905-11ea-9dfb-5654c27721d0.gif)

**To Reproduce**
1. Install UTM 1.0-rc5 from the AltStore, or update it from the previous version
1. Launch UTM
1. Try to use Split View to show UTM and another app side by side
    - expected behaviors
        - I can use Split View
    - actual behaviors
        - I can't use Split View

However, when I built from source, I can use Split View. So, the binary distributed via the AltStore may be something wrong.

**My Environment**
- iPadOS 13.5.5 Developer Beta 1
- AltStore 1.3.4b3
- macOS 10.15.4
- Xcode 11.5

**Comment by osy86** [comment]
It appears to be a bug with AltStore. I dumped the app installed by AltStore and found that the Info.plist is missing the key `UISupportedInterfaceOrientations~ipad` even though the key exists in the unsigned IPA. iOS will automatically disable split view if it does not detect `UISupportedInterfaceOrientations` or `UISupportedInterfaceOrientations~ipad` supporting all 4 orientations. On iPhone we disable the upside-down orientation because of the notch.

**Comment by osy86** [comment]
Fixed in AltStore
