### ISSUE TITLE
Should the New from template option be reworded?

### ISSUE THREAD

**Issue by ktprograms** [utmapp/UTM#3705]
If I understand it correctly, this menu item will use the VM as a template to create a new one, whereas `New from template...` implies that you're going to select a template and use it to create a new VM.

Should it be reworded to `Use as template...` or something else?

**Comment by osy** [comment]
I don't think so because "New..." implies you are creating something new (see menus like "New File" "New Project" "New Window" etc). "from template" implies you are using **something** as a template. But what? Well it's the thing you have currently right clicked on. It would be bizarre if you right click on a *specific vm* and then are prompted to select another template right? This would be more consistent with other usage of "New". "Use" is too generic of a verb to mean much. What are you using it for? What will happen when you use it? Where does it get used?

**Comment by ktprograms** [comment]
@osy Yes, that's true, however "New from template" implies that _something_ is already a template.

**Comment by osy** [comment]
Yes, the template is the thing you currently have selected.

**Comment by ktprograms** [comment]
Ok I guess that's fine since I can't think of any other way to reword it.

**Comment by makstr** [comment]
how is this different from cloning?

**Comment by blue928** [comment]
I agree this is very confusing. As a native English speaker, "New from template..." means that I am going to select a pre-created template file of some type, allowing me to avoid typing in all the config information I would do so normally.

Personally, I'm looking for an "export" function I can call on a previous VM I setup manually. I would expect that function to export a YAML, JSON, or XML file that I could change certain config parameters. 

When I click "New from template..." I would expect to be able to select this file, and a new VM be setup automatically / unattended.

This is how VMWare and Virtualbox work, so the behavior is trained into a lot of users of those other technologies.

I still do not know what "New from template..." does or if the functionality I'm looking for is possible.
