### ISSUE TITLE
VMs stored in external drives show up as 0 KB

### ISSUE THREAD

**Issue by osy** [utmapp/UTM#3724]
Another great release, working just fine on my M1 Air. Just one small thing. All my VMs are stored on my external SSD. UTM reports the size for all them as Zero KB...

_Originally posted by @brunocastello in https://github.com/utmapp/UTM/discussions/3719#discussioncomment-2300958_

**Comment by brunocastello** [comment]
Thanks @osy . A few hours ago, I discovered that it gets fixed when I remove the VMs from the list in UTM, and I re-add them one by one. Now it reports the size.

**Comment by ktprograms** [comment]
@osy I think the problem is that the VM shortcut isn't accessed in the computeSize method, so `resourceValues.totalFileSize` returns `nil`.
 https://github.com/utmapp/UTM/blob/ffa1586d73be1f52e832314ee934e85ddc3a21a2/Platform/UTMData.swift#L550

I'm not sure how calling the `vm.accessShortcut` method should be called since that either needs async/await or a callback, and this method is called to be used as a property in SwiftUI.
