### ISSUE TITLE
windows 11 network config 

### ISSUE THREAD

**Issue by 809662683** [utmapp/UTM#3841]
**Describe the issue**
install windows 11 , network config step "let's connect to network" doesn't have network option or show input network（look at the picture below） , did i config something wrong , thanks!

**Configuration**
* UTM Version: 3.1.5
* OS Version: macOS Monterey 12.2.1 (21D62)
* Intel or Apple Silicon? 
 Apple Silicon

<img width="800" alt="image" src="https://user-images.githubusercontent.com/489672/160244778-abd46dee-7bcd-4f4b-9ea2-cf35273e5ab8.png">

**Comment by lockieluke** [comment]
Try [this](https://pureinfotech.com/bypass-internet-connection-install-windows-11/)

**Comment by computerwizjared** [comment]
I added the VM tools ISO, booted the VM up, used `Shift+F10` to navigate to the D: drive and run the installer, and then installed it. Rebooted again and the installer was able to connect to the internet using the drivers that were installed.

**Comment by 809662683** [comment]
@

> Try [this](https://pureinfotech.com/bypass-internet-connection-install-windows-11/)

thank you, i finnaly success by your reply!

**Comment by abulka** [comment]
> Try [this](https://pureinfotech.com/bypass-internet-connection-install-windows-11/)

Those instructions are for an older version of the Windows installer and not applicable to more recent technical previews of of Windows 11 ARM being released by Microsoft.  

Specifically, as of March 28, 2022, it's near impossible to get past the show stopping "lack of network" error page when installing e.g. `Windows11_InsiderPreview_Client_ARM64_en-us_22579.VHDX`. The Windows installer doesn't seem to offer an offline option anymore - thus the official UTM [Windows 11 ARM installation instructions](https://mac.getutm.app/gallery/windows-11-arm) on Apple Silicon are incomplete and will fail, because networking does not work in UTM during the installation stage.

> I added the VM tools ISO, booted the VM up, used Shift+F10 to navigate to the D: drive and run the installer, and then installed it. Rebooted again and the installer was able to connect to the internet using the drivers that were installed.

Like @computerwizjared, I figured out the same way to enable networking during the installation. The steps in more detail are
- Follow the official UTM [Windows 11 ARM installation instructions](https://mac.getutm.app/gallery/windows-11-arm) but before running the vm, do the following 
- Download the [spice guest tools iso](https://mac.getutm.app/support/) 
- In UTM vm settings add a drive, browse to the spice ISO, change the drive type to CDROM.
- Run the vm and begin the installation process
- Optionally hold ESC as you boot the vm to get into the BIOS.  Then select Device Manager → OVMF Platform Configuration, Change Preferred Resolution for Next Boot to be 1024x768, save and exit out to the top level bios menu and hit CONTINUE
- When stuck at no networking available, hit `SHIFT F10` to get a windows command prompt, type `D:` then run `spice…exe` which installs the networking drivers - do not reboot. `ALT-Tab` to get back to the installer - networking will come alive and you will be able to proceed with Windows 11 installation. 

Arguably the official instructions should be updated with the above steps, unless someones has a better solution.

**Comment by thedevopsguyblog** [comment]
How do i press `SHIFT F10` from a Mac Keybaord?
`fn + SHIFT + F10`

**Comment by airtonfa** [comment]
> > Try [this](https://pureinfotech.com/bypass-internet-connection-install-windows-11/)
> 
> Those instructions are for an older version of the Windows installer and not applicable to more recent technical previews of of Windows 11 ARM being released by Microsoft.
> 
> Specifically, as of March 28, 2022, it's near impossible to get past the show stopping "lack of network" error page when installing e.g. `Windows11_InsiderPreview_Client_ARM64_en-us_22579.VHDX`. The Windows installer doesn't seem to offer an offline option anymore - thus the official UTM [Windows 11 ARM installation instructions](https://mac.getutm.app/gallery/windows-11-arm) on Apple Silicon are incomplete and will fail, because networking does not work in UTM during the installation stage.
> 
> > I added the VM tools ISO, booted the VM up, used Shift+F10 to navigate to the D: drive and run the installer, and then installed it. Rebooted again and the installer was able to connect to the internet using the drivers that were installed.
> 
> Like @computerwizjared, I figured out the same way to enable networking during the installation. The steps in more detail are
> 
> * Follow the official UTM [Windows 11 ARM installation instructions](https://mac.getutm.app/gallery/windows-11-arm) but before running the vm, do the following
> * Download the [spice guest tools iso](https://mac.getutm.app/support/)
> * In UTM vm settings add a drive, browse to the spice ISO, change the drive type to CDROM.
> * Run the vm and begin the installation process
> * Optionally hold ESC as you boot the vm to get into the BIOS.  Then select Device Manager → OVMF Platform Configuration, Change Preferred Resolution for Next Boot to be 1024x768, save and exit out to the top level bios menu and hit CONTINUE
> * When stuck at no networking available, hit `SHIFT F10` to get a windows command prompt, type `D:` then run `spice…exe` which installs the networking drivers - do not reboot. `ALT-Tab` to get back to the installer - networking will come alive and you will be able to proceed with Windows 11 installation.
> 
> Arguably the official instructions should be updated with the above steps, unless someones has a better solution.

This works great Abulka, just one small hint for those that are pressing Shift+10 and nothing is happening. The prompt window is behind the installation, so you need to use Alt+TAB to show it and install the spice tools as the instructions above.
