### ISSUE TITLE
Apple Virtualization Linux VMs are unavailable after upgrade from Big Sur to Monterey host

### ISSUE THREAD

**Issue by ktprograms** [utmapp/UTM#4023]
**Describe the issue**
I have an Apple Virtualization Linux VM, which was showing up fine on Big Sur, but after I upgraded to Monterey, it shows as Unavailable, and can't be imported either.

I created a new Apple Virt VM, and compared the `config.plist` files. It seems like `displays`, `isAudioEnabled`, `isKeyboardEnabled` and `isPointingEnabled` are needed to be a valid VM for UTM running on Monterey. I confirmed this by adding those fields to the old VM and it imports fine.

**Configuration**
* UTM Version: 3.2.3 (57)
* OS Version: Monterey 12.3.1
* Intel or Apple Silicon? Apple Silicon

**Crash log**
N/A

**Debug log**
N/A

**Upload VM**
[config.plist.txt](https://github.com/utmapp/UTM/files/8698683/config.plist.txt)

**Comment by osy** [comment]
Oh good catch.

**Comment by afh** [comment]
Off topic: I'm trying to get an Apple Virtualisation Linux VM running with UTM. @ktprograms or anyone else reading this, would you be able to provide some information / a few pointers on how / where you've obtained the `vmlinuz` and `initframfs` images and the boot options?

I've been trying to mount different ISO images ([NixOS](https://nixos.org/download.html#nixos-iso), [Alpine](https://www.alpinelinux.org/downloads/), [Arch](https://pkgbuild.com/~tpowa/archboot-images/aarch64/latest/)), copy the kernel and init RAM disk to a location on my Mac available to UTM and boot the VM, yet the NixOS just shows a blank black screen and the alpine and arch images cannot be mounted due to:

```
% file alpine-standard-3.15.4-aarch64.iso
alpine-standard-3.15.4-aarch64.iso: ISO 9660 CD-ROM filesystem data (DOS/MBR boot sector) 'alpine-std 3.15.4 aarch64' (bootable)
% hdiutil mount alpine-standard-3.15.4-aarch64.iso
hdiutil: mount failed - no mountable file systems
% file archlinux-archboot-2022.05.16-18.15-aarch64.iso
archlinux-archboot-2022.05.16-18.15-aarch64.iso: ISO 9660 CD-ROM filesystem data (DOS/MBR boot sector) 'ISOIMAGE' (bootable)
% hdiutil mount archlinux-archboot-2022.05.16-18.15-aarch64.iso
hdiutil: mount failed - Resource temporarily unavailable
```

Or UTM fails with `Internal Virtualization error. The virtual machine failed to start.`, which I assume is due to my incorrect configuration for the VM.
