### ISSUE TITLE
Support for iOS 15 without Jitterbug

### ISSUE THREAD

**Issue by Grandboy46** [utmapp/UTM#4388]
Hello,

As you all know, TrollStore got released for iOS 14.0 -  15.1.1 and I have an iPhone 13 Pro Max on 15.1.1. However, I heard that UTM crashes when installed with TrollStore due to no jailbreak. But TrollStore uses a CoreTrust Bug and a kernel exploit to make spas permanently signed and I want to know if it is possible to support UTM up to 15.1.1 without jailbreak or Jitterbug using these exploits?

**Comment by osy** [comment]
https://github.com/opa334/TrollStore/issues/102

As they explained, the issue is that the signing bug prohibits dynamic-codesigning so JIT apps are not supported. We’re looking into why trollstore installed apps won’t work with jitterbug (and I assume jitstreamer). But until that’s resolved, you can install UTM normally and Jitterbug with trollstore.

**Comment by khanhduytran0** [comment]
You can still fallback to W^X JIT.
I think one can have `com.apple.private.security.no-container` and `com.apple.private.persona-mgmt` to spawn a process as root that can be used to attach the parent process(?)

**Comment by gbowsky** [comment]
I think this issue should be reopened as there is a new possibility to obtain self-JIT with TrollStore
https://github.com/PojavLauncherTeam/PojavLauncher_iOS/commit/ccaa941

**Comment by osy** [comment]
https://twitter.com/UTMapp/status/1569926120388034562
