### ISSUE TITLE
"Network dropped connection on reset" errors on 9p mounts

### ISSUE THREAD

**Issue by lloeki** [utmapp/UTM#4394]
Simple: add a 9p share to a VM (here I used the Debian Minimal one from UTM, updated to bullseye), mount it, and try to look at things on the host from the VM.

```
root@debian:~# mount -t 9p -o trans=virtio share /mnt/Users -o version=9p2000.L
root@debian:~# touch /Users/lloeki/foo
root@debian:~# ls -l /Users/lloeki/foo 
root@debian:~# ls -l /mnt/Users/lloeki
ls: /Users/lloeki/foo: Network dropped connection on reset
-rw-r--r-- 1 root root 0 Sep  9 05:21 /Users/lloeki/foo
```

This has been reported at lima:
- https://github.com/lima-vm/lima/issues/831

This is caused by a errno mapping issue between Darwin and Linux, fixed in QEMU 7.1:
- https://gitlab.com/qemu-project/qemu/-/issues/1010
- https://gitlab.com/qemu/qemu/-/commit/f5643914a9e8f79c606a76e6a9d7ea82a3fc3e65

So, I guess the fix is "easy": update to QEMU 7.1 :D

**Configuration**  
* UTM Version: 4.0.2 (61)
* macOS Version: 12.5.1 (21G83)
* Mac Chip (Intel, M1, ...): M1

**Comment by sbates130272** [comment]
Hmmm I am on QEMU 7.1 and I still see this issue. UTM 4.0.5. Ubuntu 22.04 guest.

**Comment by sbates130272** [comment]
An strace inside the guest yields lots of these:
```
lgetxattr("/mnt/host/zlib-ng", "security.selinux", 0xaaaafc97e8b0, 255) = -1 ENETRESET (Network dropped connection on reset)
```

**Comment by sbates130272** [comment]
@osy can you see if you can replicate this on QEMU 7.1 and then assign as a bug rather than future if the QEMU fix did not resolve this issue (and I do not think it did).

**Comment by osy** [comment]
That’s… that’s not how it works. UTM is based off of QEMU. It doesn’t pull QEMU from your system. It’s built in.

**Comment by sbates130272** [comment]
@osy doh. Ooops. Thanks for the clarification. Sorry for being such a noob. So I guess I need to wait for UTM to bump to 7.1 and see if this issue goes away.

**Comment by sbates130272** [comment]
@osy sorry to be a pain but where in the codebase does UTM pull in QEMU? I had a look but I can't find anything obvious. I'd appreciate a pointer. Thanks!

**Comment by osy** [comment]
https://github.com/utmapp/UTM/blob/main/Documentation/Dependencies.md

**Comment by sbates130272** [comment]
Thanks @osy for helping me out. That all makes much more sense now. Looking forward to the upgrade to 7.1!

**Comment by anttiryt** [comment]
this started happening to me after standby/resume from UTM.

**Comment by lelegard** [comment]
Hi,

Could you please tell when UTM 4.1 will be released? I have the same issue and wait for a fix.

Alternatively, could anyone indicate how to modify the qemu command line which is generated by UTM to use qemu 7.1.0, as installed by Homebrew?

I tried without luck. 
- Using QEMU / Export command from UTM, the generated command starts with `qemu-system-aarch64 -L /Applications/UTM.app/Contents/Resources/qemu ...`
- The default `qemu-system-aarch64` is the one from Homebrew (7.1.0). When I try to run the command, it says `qemu-system-aarch64: -spice: invalid option`
- Using `ps`, I see that the actual process is `/Applications/UTM.app/Contents/XPCServices/QEMUHelper.xpc/Contents/MacOS/QEMULauncher.app/Contents/MacOS/QEMULauncher /Applications/UTM.app/Contents/Frameworks/qemu-aarch64-softmmu.framework/Versions/A/qemu-aarch64-softmmu` instead of `qemu-system-aarch64`. So, I tried it but it failed immediately with `Trace/BPT trap: 5`.
- Using `htop`, I see that `QEMULauncher` is in fact a child process of `QEMUHelper`. But the latter has no command line argument and must have been created using some specific configuration. If I try to run it, I get `An XPC Service cannot be run directly`.

So, is there a simple way to tweak the UTM-generated qemu command using another instance of qemu, namely the version 7.1.0 which is installed with Homebrew?

**Comment by osy** [comment]
https://github.com/utmapp/UTM/releases Please check out 4.1.1 beta. QEMU has been updated.

**Comment by lelegard** [comment]
> [ttps://github.com/utmapp/UTM/releases](https://github.com/utmapp/UTM/releases) Please check out 4.1.1 beta. QEMU has been updated.

Thanks, works great, no more "network dropped" error.
