### ISSUE TITLE
Disallow editing most VM settings when VM is paused

### ISSUE THREAD

**Issue by ThatsNiceGuy** [utmapp/UTM#476]
(Feature suggestion)

Disallow editing the following settings when the VM is paused:
- System section
  - Everything
- Display section
  - Type (full graphics/console mode)
- Input section
  - Legacy PS/2 Mode
- Networking section
  - Hardware (enabled/disabled and network card selection)
- Sound
  - Everything
- Sharing
  - Directory sharing on/off toggle

Also for better UX, tell the user ‘These settings can’t be edited while the VM is paused or running’

**Comment by IIWare** [comment]
Here is why: **for example**, you are booting a UTM VM with 4 Cores of CPU and you have Windows 7, if it allows you to pause it, and change it to 2 Cores of CPU and then resuming it, Windows 7 expects 4 Cores, while in reality it's in 2 cores, so it runs processes that take up almost 4 cores, while it's in 2 Cores which might end up using the entire CPU that could cause stuff like heating issues, so that's why it doesn't let you edit while it's in pause.

**Comment by DudeJCApple123** [comment]
Ok

**Comment by yqs-github** [comment]
I agree.If users edit some VM settings , the VM may be not working.
