### ISSUE TITLE
utmctl bugs

### ISSUE THREAD

**Issue by ktprograms** [utmapp/UTM#4820]
**Describe the issue**  
Here's some bugs I've found while testing `utmctl`:
- [ ] "Closing this window will kill the VM" shown after suspending and trying Cmd+W when not using `--save-state`. It seems like without `--save-state` suspending just kills the VM. Also see next item.
- [ ] Suspend errors not shown either in window or utmctl when not using `--save-state`.
- [ ] Unclear what suspend without `--save-state` does.
- [x] #4884
- [ ] Debug logging doesn't appear to change any output.
- [x] #4850
- [ ] Make force/kill/request mutually exclusive in help for stop command. The "standard" for this is to use `|` (alternator) like this: `[--force|--kill|--request]`.
- [x] #4849

**Configuration**  
* UTM Version: 4.1.2
* macOS Version: 12.5.1
* Mac Chip (Intel, M1, ...): M1

**Comment by osy** [comment]
- "Debug logging doesn't appear to change any output."
This is intentional. There is no debug logging yet.

- "Make force/kill/request mutually exclusive in help for stop command."
I want to do this but I don't know how to do it in swift-argument-parser, if you figure it out, let me know.

**Comment by ktprograms** [comment]
>Make force/kill/request mutually exclusive in help for stop command.

This doesn't seem to currently be possible in swift-argument-parser. I might submit a PR for it in the future, but for now, can you consider adding "exclusive with <b>,<c>" to the help text for each option?

**Comment by osy** [comment]
* Unclear what suspend without --save-state does.
It does exactly that: it suspends the VM execution WITHOUT saving the state. It is useful, for example, if you don't want to waste CPU cycles or battery. Note that the Pause button in the GUI will ALWAYS attempt a "save" after suspend so this is a function that's not available in the GUI.

* Suspend errors not shown either in window or utmctl when not using --save-state.
I am unable to reproduce this. I think you are mistaking the error from "save-state" with the error from "suspend". For example, if you are running x86 hypervisor or virgl, save state is not supported but suspend IS supported (for the point above, the GUI will say it's an error with suspend, but it's actually an error with save). So not seeing an error when executing the CLI suspend command but seeing an error pressing the Pause button is expected.

* "Closing this window will kill the VM" shown after suspending and trying Cmd+W when not using --save-state.
This is also intentional. Remember that when you suspend without "save-state" you are not saving the state and so if you then close the window, you will lose data.

* It seems like without --save-state suspending just kills the VM.
I am unable to reproduce this. I tried "suspend" followed by a "start" and it resumes at the same point.

* can you consider adding "exclusive with ," to the help text for each option?
The help text is generated by swift-argument-parser. I'm sure there's a way to override it but I think it'll be excessive just for this comment. If swift-argument-parser gains the ability to do exclusive options, then the help text should be updated to match.

**Comment by ktprograms** [comment]
Thanks for explaining the difference between suspend and --save-state. That was the cause of my misunderstanding for the first 4 points in your reply.

So without `--save-state`, the VM state is only kept in the QEMU process, but not saved to disk, right?

If so, do you think there should be something in the help text to make that clear (since when I was looking at it, I assumed it was just replicating the behaviour of the GUI). The help text for the `--save-state` option does say it, but because I didn't know QEMU could suspend without saving state, I wasn't sure why the option would be needed.

**Comment by osy** [comment]
Updated in https://github.com/utmapp/UTM/commit/9d6e59f5ef693fa9b33a6380272e3935fb238238

Please close this issue if you are satisfied.

**Comment by ktprograms** [comment]
Thanks
