### ISSUE TITLE
Floppy drive is read-only (regression of #3333?)

### ISSUE THREAD

**Issue by CmptrExpr** [utmapp/UTM#4925]
The floppy drive always has the read-only attribute turned on in the configuration. There is no way to turn it off via UTM.  When I try to format the floppy, it seems to work until the end of the format where the format command (DOS) complains about a read-only drive.

**Configuration**  
* UTM Version: 4.1.5
* macOS Version: 13.1
* Mac Chip (Intel, M1, ...): M2

**Comment by osy** [comment]
Okay, this is a documentation/UI issue and I need to think more about it. If you create a removable drive (New -> Removable checked -> Browse/Create) then mount a floppy image from the settings or the home screen, it will be read-only. This is consistent with other removable images like ISO CD drives. If you import a non-removable drive (New -> Removable unchecked -> Import) and select the floppy image. You can create a "fixed" floppy drive with an image permanently attached. Note you are allowed to create two floppy drives (one removable and one fixed).

UTM currently does not support writable removable images. Any data that is writable must be inside the VM .utm bundle which is what happens when you create a fixed drive. Let me know if this works @CmptrExpr and I will try to write something in the documentation about this.

**Comment by CmptrExpr** [comment]
I can see how you might think this way given a limited perspective. However, as an emulator, even CD drives (which also support CD-RW and DVD-RW) have write capability in the real world. And they are removable. In my particular case I only need the floppy to be writable and removable.

Granted, if you have multiple discs (either CD or floppy), the general use case is read, not write. However, that is not always the mode of operation - multi-discs sets need to be created somehow to have the ability to make them read-only. It is very cumbersome to have to reload the virtual machine when having to do this.

A method to create the multi-disc set outside of the VM would go a long way toward alleviating the aggravation.

On the other hand, I don't have any problem placing all of the media inside of the .utm bundle so long as I get to switch between media when the installation program calls for it.

**Comment by osy** [comment]
Okay I’ll consider it as another argument for #5079 which I’ll use to track this request
