### ISSUE TITLE
[CocoaSpice] Display stream overlay

### ISSUE THREAD

**Issue by utmapp** [utmapp/UTM#5]
Need to implement the event handler and gstreamer hooks.

**Comment by osy86** [comment]
Upon farther research into this feature it does not appear to be needed. This SPICE feature allows fast moving images to be encoded into a video stream (with optional compression/encoding) in order to save bandwidth. This is because SPICE is originally designed for interfacing remote VM. Since we are running both the client and server locally, bandwidth is not an issue and the additional overhead of encoding/decoding video frames is not worth it.
