### ISSUE TITLE
UTM 2.0 B6, unable to create virtual disks in IOS 14.2

### ISSUE THREAD

**Issue by cs-sugar** [utmapp/UTM#505]
In the version of UTM 2.0 B6, the virtual disk cannot be created in IOS 14.2. The file name cannot be modified when the disk is created. After creation, it will be displayed as shown in the following video and cannot be started.
<videosrc="http://chtgyunbackup.cloud.sakura8888.moe/UTM/bug/issueingithub/video/issue%20UTM%202.0%20B6%2C%20unable%20to%20create%20virtual%20disks%20in%20IOS%2014.2%20video/IMG_0297.MP4"controls></video>

**Comment by cs-sugar** [comment]
If the video cannot be displayed, please click the link below:
http://chtgyunbackup.cloud.sakura8888.moe/UTM/bug/issueingithub/video/issue%20UTM%202.0%20B6%2C%20unable%20to%20create%20virtual%20disks%20in%20IOS%2014.2%20video/IMG_0297.MP4

**Comment by IIWare** [comment]
before making a bug issue, please do the following:

1. make sure you're using the latest version of utm
2. if you find a bug, before reporting a utm bug, check for the same utm bug report existing in utm issues.
3. if the same utm bug report you wanted to report, isn't in utm issues, you can report the bug, but you need to be in the latest version of utm before reporting a bug.

so please use utm v2.0b7 and if the bug is in the latest version you can report the bug.

**Comment by osy86** [comment]
Sorry, I should make this more obvious. Removable drives are no longer managed in that page. Once the VM is saved, you can set the ISO from the main details view. I will add a popup alert the first time to make this more clear.

**Comment by brunocastello** [comment]
I have a similar problem with 2.0.8. I have a Windows 98 SE VM with two CD-ROM images for two games, needed to run them. I’ve set a CD/DVD removable image drive for that matter. The removable option in Drives for this drive is greyed out for some reason. I’ve chosen the image of a CD-ROM (NBA97CD.iso RAW format) through the VM details page before starting the VM. But when I start the VM, the CD-ROM is not there (and neither is through the CD icon to swap it). I can choose any image, but the swap image is not working either.

And if I set a CD/DVD image which is not removable, works. However, when I decide to remove it and use a different image before booting the VM, the entry for that drive is removed but the image is not deleted from the .UTM VM “images”folder. With UTM 1.0 it worked flawlessly, but since 2.0 it does not.

My original plan was to keep a “CDs” folder inside UTM folder to store my CD images to use with the removable option.
