### ISSUE TITLE
Data storage with secondary image on external disk

### ISSUE THREAD

**Issue by nerdlich** [utmapp/UTM#5079]
I've read #3484, but does it mean that I cannot add a secondary disk on an external drive of the host, i.e. outside the utm bundle? The UI lets me do it. I can create a qcow2, import it as virtio and start the guest. The guest sees the disk as /dev/vdb and I can move files to it. After shutting down the vm, the settings screen shows the correct usage of each disk. However, on host OS level, all the data ends up in the original qcow2 image inside the utm bundle. The new image on the external disk is still just kilobytes.

**Configuration**  
UTM Version: 4.1.5 (74)
macOS Version: 13.2.1
Mac Chip (Intel, M1, ...): M1

```
# df -h
Filesystem                         Size  Used Avail Use% Mounted on
/dev/mapper/ubuntu--vg-ubuntu--lv   98G   17G   77G  18% /
/dev/vda2                          2.0G  129M  1.7G   8% /boot
/dev/vda1                          1.1G  6.4M  1.1G   1% /boot/efi
/dev/vdb1                          3.4T  227G  3.0T   7% /srv
```

[config.plist.zip](https://github.com/utmapp/UTM/files/10855373/config.plist.zip)

**Comment by nerdlich** [comment]
Realized that the additional images get copied to the UTM bundle. Is support for external disks planned, or is there a workaround?

**Comment by ktprograms** [comment]
Wild guess, but if you add it as a removable drive, I think it won't copy the disk into the bundle. By default the UI switches the interface to USB when you enable Removable, but I think you can switch it to VirtIO and it'll still work fine.

**Comment by osy** [comment]
We had some discussion about this in the past but the belief is that we only need to support the following use cases:
1. All disk images are inside the bundle
2. The bundle can be moved anywhere, including to external drives
3. You can add removable disk images that are read-only (similar to CD drives)

We didn't think there was any use in supporting read-write images external to the bundle and supporting it would lead to confusion when the bundle is moved around. Can you explain what you are trying to achieve?

**Comment by nerdlich** [comment]
I understand your reasoning and it certainly makes sense in a desktop setting. My use case is a (semi) headless server with a virtual OS volume on the internal SSD and data and backup volumes intended to be on USB HDDs. I solved it now by sharing '/Volumes' via virtfs, which gives the VM access to 'Macintosh HD' too, but I choose to ignore that :)
I did not like that removable disks have to be reattached manually after restarting UTM or MacOS.

**Comment by pmsjt** [comment]
No, these cases are not sufficient. If all you needed were internal RW drives and external RO drives, then USB thumbdrives would not exist. Alas they do. They do because having external RW media is a thing.

I also want to point out that the UI does allow the selection of an external USB **disk** (not CD), but then it proceeds to ignore the setting and will translate that into a QEMU CD external drive regardless.

**Comment by wggrte** [comment]
Hello! I came across this limitation while utilizing UTM for testing. I built a wrapper around UTMs applescript capabilities where I can quickly create and start VMs from a yaml file (an ansible inventory file that I further use to provision the just spawned VMs).
For convenience and unity I'd like to have all VM related files and disks in one directory, I understand that this is a preference that only I might have. So I configured the main disk as removable VirtIO disk but the vm wouldn't start because of "failed to get 'write' lock".
But another time I came across this limitation was when I wanted to mount the main disk from one machine into the other (to change the root fs). Adding the disk as removable VirtIO drive, image type disk results in the same "failed to get 'write' lock" error. I'm no qemu expert but to check if the disk was fine I manually ran a simple qemu command and booted from it.. I also tried using the USB interface as @pmsjt mentioned that, but also ran into the same error.

As far as I understand the current way to do this would be:
- Import main disk to second vm
- after changes replace main disk on first vm with changed disk from second vm
- delete disk from second vm

Is there a better way to achieve this?
