### ISSUE TITLE
Develop a UTM without sandboxing

### ISSUE THREAD

**Issue by narukeu** [utmapp/UTM#5169]
**Describe the issue**  
Sandboxed applications cannot store virtual machines on an external hard disk, which is not conducive to hard disk storage, and my hard disk does not have enough space for me to store so many virtual machines.
If I use what is said on the network, create a virtual disk image, and then mount this image into a UTM container, I have tried this method, it will lead to instability of the virtual machine and even the host operating system.

I believe that many users have an urgent need to store virtual machine files on an external hard disk, and I hope this suggestion can be accepted.

**Configuration**  
* UTM Version: Latest Version
* macOS Version: 13.3
* Mac Chip : Apple Silicon

**Comment by galaxy4public** [comment]
You can attach the virtual disk as a removable media, then its location can be anywhere.  I am doing exactly that since I don't want to sacrifice sandboxing (a security feature) for convenience.  However, please check #5170 for the current inconvenience (the removable drives are turning read-only on the UTM shutdown).

**Comment by narukeu** [comment]
1. Can virtual removable disk image be used as a system disk for OS?

2. If the system disk can exist as a removable disk, can UTM develop the function of **skipping the creation of the internal hard disk**, because this function can ignore the creation of the virtual built-in hard disk and directly create an external virtual removable disk.

Thank you!

**Comment by galaxy4public** [comment]
1. I don't see why not -- all in all this is how you install a Linux distro: you boot from the removable disk image.
2. Yeah, this would be nice, currently it forces you to create one (but you can re-arrange stuff before the VM launch, IIRC)

**Comment by narukeu** [comment]
So, for the 2nd topic, do I need to open an issue again to suggest them to implement this function?

**Comment by narukeu** [comment]
I've decided that I'll close this issue and create a new one.

**Comment by narukeu** [comment]
#5172

**Comment by narukeu** [comment]
I think releaseing a sandboxed UTM for macOS does more harm than good, so I think it's worth publishing an unsandboxed UTM.

**Comment by osy** [comment]
Classic XY problem. Having sandbox is a reason that physical drives cannot be accessed directly but removing sandboxing does not automatically mean that such a feature will be supported. #5051 is one example of a feature request for booting off a physical drive. Sandboxing is good practice for **all** apps because it prevents malware that compromises your app (or a malicious app) from doing any damage to your system.
