### ISSUE TITLE
[utmctl] Support specifying Virtual Machine by path

### ISSUE THREAD

**Issue by DUOLabs333** [utmapp/UTM#5445]
Example: `utmctl start ~/A/B.utm --hide -d`.

**Comment by osy** [comment]
Since `utmctl` is sandboxed, it will not be able to access any path that's outside the UTM sandbox. That's largely why we avoided any command that requires file paths as arguments. Do you have any other use case?

**Comment by DUOLabs333** [comment]
No, that was it --- maybe ask for permission to at least the user's home directory?

**Comment by osy** [comment]
That's not possible because CLI tools do not support asking for permissions. This is a long standing issue with macOS sandbox apps (there's not many CLI sandbox apps and that's one of the main reasons why). The AppleScript interface does work with passing unsandboxed paths so you can use that if you need.
