### ISSUE TITLE
[Beta Only]: After a while, VM gets paused and can not be unpaused

### ISSUE THREAD

**Issue by DUOLabs333** [utmapp/UTM#5489]
**Describe the issue**  
After a while (maybe around a day), the VM's screen gets frozen and can't be unfrozen. All operations in the VM also freezes, so it's not a graphical issue. The VM must be restarted. 4.2.5 does not have this problem.

**Configuration**  
* UTM Version: 4.3.2
* macOS Version: 11
* Mac Chip (Intel, M1, ...): M1

**Crash log**  

**Debug log**  
[debug.log](https://github.com/utmapp/UTM/files/12140227/debug.log)

**Upload VM**

**Comment by DUOLabs333** [comment]
Posted debug log: it seems the problem might be here:
`If one of the threads is != io-thread && != vcpu-thread, this might be a BUG`

**Comment by osy** [comment]
Do you have a way to reproduce this issue?

**Comment by DUOLabs333** [comment]
That's the problem, I'm not sure exactly what causes it. However, it seems to occur whenever some CPU- and RAM- intensive operation is happening in the VM and the window is not focused.

**Comment by neldredge-unco** [comment]
This sounds a lot like #5477, similar symptom and same log message.

**Comment by DUOLabs333** [comment]
If that's true, then it should be fixed in the next (beta) release.

**Comment by DUOLabs333** [comment]
I also noticed that just before "the Freeze", Memory Pressure spikes briefly into the yellow. Maybe that has something to do with it?

**Comment by DUOLabs333** [comment]
This happened a few more times, and I noticed that the window does not to be unfocused for the VM to freeze.

**Comment by DUOLabs333** [comment]
To make things even more interesting, the last time this happened to me, I experienced what I think was (my first) kernel panic --- my screen had jagged pink lines, then my computer restarted.

**Comment by osy** [comment]
@DUOLabs333 can you test the latest beta? Also if it happens again, would it be possible to provide a clean copy of your VM without any personal data that can be used to reproduce the bug? Right now I have an ubuntu 22.04 installation I left on for multiple days and am not able to witness this issue.

**Comment by DUOLabs333** [comment]
It looks like this has not happened, though I will use it for one more day to confirm.

**Comment by DUOLabs333** [comment]
The freeze happened again mere minutes after I started the VM.

**Comment by osy** [comment]
Please provide some more info since I can’t reproduce it.

**Comment by neldredge-unco** [comment]
Possibly #5505 is related?

**Comment by osy** [comment]
I don’t think so, why

**Comment by DUOLabs333** [comment]
No --- it's weird, it seems to happen randomly, and I can't find what causes it (on the bright side, it seems that the Memory Pressure doesn't rise too much anymore over time).

**Comment by osy** [comment]
Can you build a new VM with a similar configuration and post it?

**Comment by DUOLabs333** [comment]
Post the utm file or the config.plist?

**Comment by mx1up** [comment]
Linux VM hangs, I think, after about 15mins. At that time, when I try to enter something in the console, it says the port is not opened.

Here is the debug log:
[qemu_debug.log](https://github.com/utmapp/UTM/files/12207750/qemu_debug.log)

I'm on M2

**Comment by osy** [comment]
@DUOLabs333 for clarification, did you see the error popup "The port is not opened"? Because I think other people are conflating issues here.

**Comment by DUOLabs333** [comment]
No, I'm actually surprised: I never got that error (now I'm scared that somehow the app didn't update, even though I see 4.3.3 in About).

**Comment by osy** [comment]
I'm digging into it more and it may be the same bug although I don't know why you aren't getting the error. That message shows up when a SPICE channel gets disconnected unexpectedly which of course would also mean everything would seem to freeze.

**Comment by mx1up** [comment]
btw, I also didn't get that error popup (port not opened) while using the display window, unless I click in the terminal window and try to write something there. I thought that error was just a side effect of the freezing..

**Comment by osy** [comment]
I see, thanks for the clarification

**Comment by DUOLabs333** [comment]
I've noticed that 4.3.3 freezes VMs much faster than 4.3.2. I donwgraded back to 4.3.2, but this change in behavior persisted.

**Comment by osy** [comment]
Can you try https://github.com/utmapp/UTM/suites/14668665657/artifacts/832453260 it should have more verbose logging which may help pin point the issue.

**Comment by DUOLabs333** [comment]
Interesting --- the fork you provided does not seem to have the problem.

**Comment by osy** [comment]
I was finally able to reproduce this issue after digging out a M1 Macbook with 8GB of RAM. I'll write up the process in case someone finds this through a search engine in the future and is wondering WTF is going on.

So basically, the effect people observed is that SPICE, the UI backend, was getting disconnected. Usually, this only happens if the server (owned by QEMU) closes the connection but after extensive logging, it seems like it wasn't following the "normal" connection termination path (i.e. when a VM shuts down). To figure out where the socket was being closed, I added an `abort()` before the `shutdown()` call in libspice which forces the QEMU process to crash when it tries to close the socket (for some reason as we'll see soon, hooking a debugger on QEMULauncher mitigates the bug). This triggers a crash and a stack trace when the socket is about to be closed and I saw that it was getting called by deconstructor call triggered by the `exit()` in https://github.com/utmapp/UTM/blob/main/QEMULauncher/Bootstrap.c#L50

That function exists to make sure the QEMULauncher process is always terminated when the parent (QEMUHelper, an XPC service) exits. Why? Because previously we witnessed a lot of zombie processes because it seems like macOS doesn't properly clean up the children of XPC processes.

So now the question is why QEMUHelper was being terminated. Turns out it is because Jetsam (part of XNU's memory management) will terminate and process it deems "idle" when the system is low on memory and an XPC process that isn't doing anything is considered "idle". This explains why it was impossible for me to reproduce the bug on my system with ample RAM. Why did this only start showing up in the beta? Because of this commit: https://github.com/utmapp/UTM/commit/03d200422f78707320ea27af88ab73dc8334ea85 as part of the refactor, the way the QEMU process termination event handling was changed. Previously, the `startQemu` XPC call returned (via callback) only after QEMU terminates. That was problematic because it was impossible to know "when" QEMU has launched leading to a bunch of race conditions between QEMU launching and SPICE launching. The change was to return after the NSTask was started and to have the XPC process make a reverse call when QEMU terminates. This works great except now the XPC service sits idle for the entire time QEMULauncher is running and XNU can decide to randomly kill it when low on memory.

So the fix is simple: we make a new XPC service call which holds on to the callback (just like before) until QEMU exits. This allows the XPC service to essentially lie to its parent about it still waiting to give a response and therefore cannot be marked idle. It seems like this is the only way to lie to Jetsam without root privilege or entitlements. Calling `proc_track_dirty(getpid(), 0)` does not seem to work. I would be curious to know if anyone has a less hacky way of going about this.

**Comment by DUOLabs333** [comment]
Just an update: I do get "port is not opened" in the log now, but still not in a dialog.

**Comment by osy** [comment]
@DUOLabs333 this is with the fix?

**Comment by DUOLabs333** [comment]
No (I don't have enough space for XCode), but with the debug fork.

**Comment by osy** [comment]
https://github.com/utmapp/UTM/suites/14685729939/artifacts/833666921

**Comment by DUOLabs333** [comment]
It seems to work well --- as a bonus, it seems the memory leak got fixed.

**Comment by arikon** [comment]
I'm trying to install Ubuntu server and it VM freezes after 10-15 minutes during install.
