### ISSUE TITLE
Automatically capture system keys when in full screen for Windows VMs

### ISSUE THREAD

**Issue by jjw24** [utmapp/UTM#5514]
**Context:**
When running a Windows 11 Pro VM on macOS host, switching the VM Window to full screen does not automatically select and mark the 'Capture input devices' icon as active. This gets annoying because every time switching back to the Windows VM need to remember to set it manually or will accidentally get the macOS keyboard shortcuts instead.

Host: macOS Ventura 13.1, M1
GuestOS: Windows 11 Pro

This feature is already implemented for Apple VMs in #3668, but not for Windows.

**Request:**
When Windows VM is in full screen mode, automatically capture system keys, select and mark the 'Capture input devices' icon as active.

**Comment by shreyanshk** [comment]
Hello,
While I hope that this fix will also automatically apply to Linux VMs but, just in case not, I would also request the same for Linux VMs.

Many thanks.

**Comment by brad** [comment]
The referenced commit did not fix this issue. Yes, when you initially enter fullscreen mode input gets automatically captured. However, if you three-finger swipe to Mac OS and back, the input does not get recaptured. You have to manually Ctrl+Option each time to recapture input

**Comment by guiambros** [comment]
Is this supposed to be fixed on Mac OS host?  I have a Linux ARM guest running on Mac OS M1 with UTM v.4.5.3 (99), and I simply can't capture input entirely. I've tried doing it manually by clicking Capture Input Devices, or pressing Option + Command, or putting in Full Screen -- neither worked.

If I use e.g. Command + Tab, it would simply open the host's (Mac's) task switcher, instead of being captured by the Linux guest.

(Glad to open a separate bug report for Mac if it makes sense; I see this one started on a Windows host)
