### ISSUE TITLE
The bootindex 0 has already been used

### ISSUE THREAD

**Issue by nsry123** [utmapp/UTM#5717]
**Describe the issue**  
When booting a x86 virtual machine in a .ova format, there is an error: "The bootindex 0 has already been used"

**Configuration**  
* UTM Version: 4.3.5 (87)
* macOS Version: 13.5.1 (22G90)
* Mac Chip:  M1 Pro

**Crash log**  
[crash.log](https://github.com/utmapp/UTM/files/12656770/crash.log)

**Debug log**  
[debug.log](https://github.com/utmapp/UTM/files/12656745/debug.log)

**Upload VM**  
The VM is the Matrix 1 from vulnhub: https://mega.nz/#!CiwBjRZB!EtKOQvDQjytMq3LkkMgrHDC9EYxEz8mqpOg5M2N1OOk

**Comment by ManuW** [comment]
<img width="1392" alt="Bildschirmfoto 2023-09-23 um 20 03 34" src="https://github.com/utmapp/UTM/assets/8384437/8c5d7f1d-e383-48ee-95e7-0e6151a04b18">

I was able to boot it.

As far as I know you cannot import OVA files in UTM. My workaround to this is following:
- Convert the virtual disk from vmdk to qcow2 format
- Create a new QEMU VM, remove all disks and import the created disk

More details:

Download the VM and convert the disk (Terminal)
```sh
~/Downloads/Machine_Matrix ▶ ls
Machine_Matrix-disk001.vmdk Machine_Matrix.ovf

~/Downloads/Machine_Matrix ▶ qemu-img convert -f vmdk -O qcow2 Machine_Matrix-disk001.vmdk Machine_Matrix-disk001.qcow2

~/Downloads/Machine_Matrix ▶ ls
Machine_Matrix-disk001.qcow2 Machine_Matrix-disk001.vmdk  Machine_Matrix.ovf
```

 UTM
1. Create a new emulated Linux system and choose some random image or dmg file
2. Then continue (if there is an error because of the image or dmg - ignore it) and the summery should appear. Under the field name select Open VM Settings and continue
3. In the settings of the VM
3.1 Remove all drives
3.2 Create a new drive and import Machine_Matrix-disk001.qcow2
3.3 Display: I had to select vritio-vga, the default was not working
3.4 Change network to host only (because of the VM should not have access to your local network)
4. Start the VM

**Comment by nsry123** [comment]
> <img alt="Bildschirmfoto 2023-09-23 um 20 03 34" width="1392" src="https://user-images.githubusercontent.com/8384437/270124314-8c5d7f1d-e383-48ee-95e7-0e6151a04b18.png">
> I was able to boot it.
> 
> As far as I know you cannot import OVA files in UTM. My workaround to this is following:
> 
> * Convert the virtual disk from vmdk to qcow2 format
> * Create a new QEMU VM, remove all disks and import the created disk
> 
> More details:
> 
> Download the VM and convert the disk (Terminal)
> 
> ```shell
> ~/Downloads/Machine_Matrix ▶ ls
> Machine_Matrix-disk001.vmdk Machine_Matrix.ovf
> 
> ~/Downloads/Machine_Matrix ▶ qemu-img convert -f vmdk -O qcow2 Machine_Matrix-disk001.vmdk Machine_Matrix-disk001.qcow2
> 
> ~/Downloads/Machine_Matrix ▶ ls
> Machine_Matrix-disk001.qcow2 Machine_Matrix-disk001.vmdk  Machine_Matrix.ovf
> ```
> 
> UTM
> 
> 1. Create a new emulated Linux system and choose some random image or dmg file
> 2. Then continue (if there is an error because of the image or dmg - ignore it) and the summery should appear. Under the field name select Open VM Settings and continue
> 3. In the settings of the VM
>    3.1 Remove all drives
>    3.2 Create a new drive and import Machine_Matrix-disk001.qcow2
>    3.3 Display: I had to select vritio-vga, the default was not working
>    3.4 Change network to host only (because of the VM should not have access to your local network)
> 4. Start the VM

That is a great answer. It booted the machine perfectly. Another important thing is to not toggle the UEFI option in the setting. Thank you very much.

**Comment by ManuW** [comment]
> Another important thing is to not toggle the UEFI option 

Yes. I forgot this. I setup the VM and then I documented this and forgot this step.
