### ISSUE TITLE
Windows 95 crashes in UTM v4.x, but not in v3.x

### ISSUE THREAD

**Issue by DavidCWGA** [utmapp/UTM#5760]
I realize that Windows 95 is probably not a priority, nor officially supported, but I'm sad that this used to work, and now it doesn't. Since UTM itself doesn't crash, this might be a qemu issue?

**Describe the issue**  
Windows 95 crashes on a suitably configured emulated i386 machine (i440FX, pentium, no UEFI, no RNG, PS/2 controller, no USB, no sharing, cirrus-vga, pcnet, sb16), but only on UTM v4.0.0 and up. Earlier versions work OK.

**Configuration**  
* UTM Version: 4.0.0+
* macOS Version: Any
* Mac Chip (Intel, M1, ...): Any

**Crash log**  
UTM doesn't crash, but Windows 95 does.

The Windows 95 installer crashes with this error:
````
SUWIN caused an Illegal Instruction in module <unknown>0A77:A025àISUWIN will close.
````

If you attempt to boot a Windows 95 image that was installed using an earlier version of UTM, Windows fails to boot and displays this error:

````
When initializing device IOS:
Windows protection error. You need to restart your computer.
````

**Debug log**  
[debug.log.gz](https://github.com/utmapp/UTM/files/12778464/debug.log.gz)

**Upload VM**  
[config.plist.gz](https://github.com/utmapp/UTM/files/12778469/config.plist.gz)

**Comment by DavidCWGA** [comment]
Yeah, it's a qemu problem. Someone else raised the same problem on the qemu gitlab here:

https://gitlab.com/qemu-project/qemu/-/issues/1759

So I guess this is not a UTM problem.

**Comment by NorseIvan** [comment]
Please, for the love of all that is holy, update UTM to reflect this fix prior to 2.5.0 release.

This issue has been resolved in a recent Qemu fix, but it hasn't been pulled for the latest 2.5.0 beta build as it's still there. Can you please update these files for the next release, beta or otherwise? This allows Windows 95 to run without additional fixes, both during setup and within the OS while changing certain drivers and settings.

The fix:
https://patchew.org/QEMU/20240117155143.172890-1-pbonzini@redhat.com/

Resolves the following 3 issues:
https://gitlab.com/qemu-project/qemu/-/issues/1759
https://gitlab.com/qemu-project/qemu/-/issues/1964
https://gitlab.com/qemu-project/qemu/-/issues/2012

**Comment by osy** [comment]
@NorseIvan we've reverted QEMU due to a list of issues in v8.0.0 including:

#5516
#5515

as well as other issues (such as #5371) that were reported but not 100% sure to be caused by QEMU. There are plans to re-integrate the latest QEMU as part of the next major release. If you want to help, help repro the listed issues and see if they are fixed with latest QEMU. Otherwise, wait patiently until I get the time to integrate and test everything.

**Comment by NorseIvan** [comment]
I'll give them a go and see if I can help. Thanks for getting back to me. I didn't know what to do about any of it and it took a bit of sleuthing to track.
