### ISSUE TITLE
Request for MacOS Virtualization on M1 iPads

### ISSUE THREAD

**Issue by gunnarfandrich** [utmapp/UTM#5776]
The M1 iPads with 1tb+ storage have 16gb of ram. Given how well windows for arm performs on UTM, it seems the M1 iPad could possibly run MacOS just as well. Would it be possible to port the features needed to run MacOS to M1 iPads?

**Comment by osy** [comment]
In theory possible with new work on vmapple running in QEMU. BUT it's gonna suck because there's not going to be GPU virtualization because Apple's proprietary ParavirtualizedGraphics framework does not exist on iOS. Maybe it's technically possible to patch up the framework to run on iOS but I'm highly skeptical and the work would be immense.
