### ISSUE TITLE
Utm stop when loading the iso

### ISSUE THREAD

**Issue by Jeremy-JYL** [utmapp/UTM#5930]
When I create a new Virtual Machine (The first one that I create), which is a windows xp 64bit vm, when I run the vm a error popout: `QEMU error: QEMU exited from an error: qemu-x86_64-softmmu: -drive if=none,media=cdrom,id=drive70AE1DA2-42B1-466A-B782-82F1FDF8BA2D,file=/Users/jeremy/Documents/Zip/winxp/Windows XP Professional 64 bit/Wiindows XP Professional 64 bit.iso,readonly=on: Could not open '/Users/jeremy/Documents/Zip/winxp/Windows XP Professional 64 bit/Wiindows XP Professional 64 bit.iso': Permission denied`

Also, when I try a different folder same thing happen.

**Configuration**  
* UTM Version: 4.4.4 (From homebrew)
* macOS Version: 14.1.1 (23B81)
* Mac Chip (Intel, M1, ...): M2

**Comment by Jeremy823** [comment]
<img width="912" alt="Screenshot 2023-11-30 at 4 47 19 PM" src="https://github.com/utmapp/UTM/assets/108569568/f7619264-40fc-4ffb-90b6-2442bff2f2e2">

**Comment by robohack** [comment]
I have the same error with an ISO image either on NFS or in my `~/Downloads` directory with my first attempt to use UTM.

Many apps now encounter permissions errors when first accessing local filesystems, but they all present a little dialog box to allow the user to grant permissions, but this does not seem to happen for UTM.

I'm running the latest UTM-4.4.5 (downloaded from the web site) on macOS 14.3 (intel)

**Comment by robohack** [comment]
Explicitly adding UTM to the list of apps with "Full Disk Access" in "Privacy & Security" settings doesn't help (unsurprisingly since it is actually the QEMU program that's getting the error).  It doesn't seem easy/possible to browse to the qemu binary inside UTM.app in order to give it full disk access.

**Comment by Jeremy-JYL** [comment]
Also, I find out only loading the Linux kernel with initrd and disk image is working
<img width="705" alt="Screenshot 2024-01-25 at 17 08 10" src="https://github.com/utmapp/UTM/assets/108569568/8a126cda-73d1-4063-83e9-06e9b0f5c736">
Note NT LINUX is just a simple Linux that I have compiled.

**Comment by magnuspraeda** [comment]
I have also tried giving UTM full disk access, but, like robohack noted, this was unsuccessful. UTM is also giving me a similar error even when the ISO is in a different directory within ~/.

**Comment by robohack** [comment]
Even moving the ISO to another unprotected separate filesystem makes no difference.

**Comment by robohack** [comment]
I learned that you can drag any (program) file from a Finder window and drop it on the "System Preferences" "Full Disk Access" panel in order to grant it full disk access, and of course with a full finder window one can navigate into the contents of an app, so I added `qemu-x86_64-softmmu` to the list.

However that did not help.  Probably this "full disk access" aspect is an unrelated distraction.

**Comment by robohack** [comment]
"Version 4.5.1 (96)" is now working A-OK for me.
