### ISSUE TITLE
Enabling TPM 2.0 device prevents booting off ISO

### ISSUE THREAD

**Issue by steverfrancis** [utmapp/UTM#5996]
**Describe the issue**  
When the TPM 2.0 option is enabled, the boot takes me to the UEFI interactive shell, as if there is no bootable device.
Yet unchecking the TPM 2.0 option allows the same VM with the same ISO to boot fine (albeit without SecureBoot, which is what I want.)

**Configuration**  
* UTM Version: 4.4.4 (93)
* macOS Version: Sonoma 14.1.2
* Mac Chip (Intel, M1, ...):  M1 Pro

**Debug log**  
VM never actually boots, so no debug log.

**Upload VM**  

[config.plist.zip](https://github.com/utmapp/UTM/files/13790278/config.plist.zip)

The ISO I am booting off can be generated from https://factory.talos.dev/
I am using Talos 1.6.1, no extensions, and downloading the Arm64 Metal SecureBoot ISO.

**Comment by cky** [comment]
You _can_ use Talos with Secure Boot, as you can see in the bottom row of the header.

![Talos with Secure Boot](https://github.com/utmapp/UTM/assets/42980/8098145d-6bc8-457e-ab13-98cdd58d8942)

Talos uses [its own signing certificate](https://factory.talos.dev/secureboot/signing-cert.pem), rather than one of the standard Secure Boot certificates. You will need to convert it to DER format (`openssl x509 -inform pem -in signing-cert.pem -outform der -out signing-cert.der`), then install it into your Secure Boot DB via UEFI setup.

**Comment by osy** [comment]
This is the intended behaviour of secure boot.
