### ISSUE TITLE
Is it possible to use Pojav Launcher Team modded ANGLE as the backend of virglrenderer

### ISSUE THREAD

**Issue by littlefish12345** [utmapp/UTM#6454]
Recently I did some research about graphics API and it seems like Pojav Launcher uses ALNGLE as a render backend which export OpenGL 3.2 and that makes me wondering wether we can uses it in UTM to provide higher version support of OpenGL. Mesa now only provides OpenGL 2.1 though virglrenderer got OpenGL ES 3.0. For some reason Mesa didn't provide higher version. Is this method possible? And if it's possible how can we implement this?

**Comment by osy** [comment]
The OpenGL version is not limited by ANGLE. The version of ANGLE we're using supports OpenGL 3.2 as well. The reason you're limited is because mesa determines the minimum supported level dynamically by probing the support from virglrenderer which does not take full advantage of ANGLE. Basically if BOTH virglrenderer and ANGLE does not support a feature, it will be marked as unavailable.

**Comment by littlefish12345** [comment]
So is there any way to work around it like set MESA_GL_VERSION_OVERRIDE or modify virglrenderer? Or support for higher version of OpenGL just simply wouldn't work for now. Btw what's the development of gfxstream now? Running vulkan inside a iOS VM is such attractive to me that I cant stop thinking about it.

**Comment by DUOLabs333** [comment]
@littlefish12345 `MESA_GL_VERSION_OVERRIDE=3.3  MESA_GLSL_VERSION_OVERRIDE=330` works *mostly* works for me --- there may be some crashes though. You should play around to see what's the highest you can go until something breaks. Even though ANGLE may not be fully compliant, depending on the application, there may be enough implemented to work.

For example, kitty requires OpenGL 3.1, but using overrides, I got it to work with OpenGL 2.1 (probably because it doesn't require full conformance). However, background rendering doesn't work properly (everything else does though).

**Comment by littlefish12345** [comment]
@DUOLabs333 Thanks for your reply. The version override method truly works. I looked at your repo and here are some advices. Why not trying some faster serialize method like protobuf or raw binary which make a lot more sense to me rather than json. And maybe try DMA into the VM instead of using network? I'm afraid that maybe I can only give these advices because I only have a M2 iPad Pro right now and I didn't find a way to run MacOS on iOS through UTM. I'm willing to help if there is anything I can do.

**Comment by DUOLabs333** [comment]
@littlefish12345 Trust me, I'm trying to make communication as fast as possible, but the network is honestly the easiest way to do it (don't need to worry about how to handle disconnects or threading). I'm not sure QEMU offers DMA functionality --- if so, please let me know. Right now, I'm working on a tool that basically acts a faster communication channel between guest and host (once set up, I'll move all of my tools to using it) --- however, it's kind of messy, and still requires the network for the coordination messages, so I don't like it too much.
