### ISSUE TITLE
UTM for Windows

### ISSUE THREAD

**Issue by oridib69** [utmapp/UTM#6538]
Hello! I’ve just discovered this app and wanted to try it. I only have a windows laptop but no MacBook. I wanted to try this app but I can’t do it, can you make a UTM for windows? Thanks!

**Comment by mirrornoir** [comment]
UTM is simply a very well designed frontend for qemu, the computer emulator, with optional virtualization support supplied depending on the operating system. You can use qemu on Windows without a frontend, but it will need to be configured via batch files or similar if you want to save the command you use to start the machine. 

I’m not aware of any _good_ frontend for qemu on Windows. AQEMU may work but I found it to be less than ideal on other operating systems. virt-manager on Linux is fantastic but limited to that platform. 

Keep in mind there are other virtualization options available on Windows such as VMware Workstation Pro (now free), Virtualbox, and the low level emulators PCem and 86box. For emulation of other modern architectures, qemu is still the most ideal. 

While it would be cool if UTM was available on Windows or Linux, I don’t see this happening due to project goals. However, I’m just a fan of the project however, so take my response with a grain of salt.

**Comment by osy** [comment]
There are no plans to bring UTM to non-Apple platforms as it's designed from the ground up with Apple technologies.
