### ISSUE TITLE
In UTM 4.6.2, Linux guest complains that `virtio-sound-device` is "not compliant with spec version 1.0"

### ISSUE THREAD

**Issue by volkert-fastned** [utmapp/UTM#6848]
@osy With UTM 4.6.2, I can indeed select `virtio-sound-device` as the Emulated Sound Card.

However, when I select that for a VM running Alpine Linux 3.20 with Linux kernel 6.6.x, it doesn't work.

In `dmesg`, it complains about the `virtio_snd` device not being compliant with "spec version 1.0":

```
~ $ doas dmesg | grep -i virtio_snd
[    0.614678] virtio_snd virtio6: device does not comply with spec
version 1.x
[    0.614727] virtio_snd: probe of virtio6 failed with error -22
```

_Originally posted by @volkert-fastned in https://github.com/utmapp/UTM/issues/6404#issuecomment-2505827359_

**Comment by volkert-fastned** [comment]
Ah, wait.

There is also an Emulated Sound Card called `Virtio sound (virtio-sound-pci)` and that one **does** work in the VM client.

A bit confusing that there is also a `virtio-sound-device` in addition to that. Maybe it can be clarified what the use of this one is, and what the difference is with the other one?

Anyway, closing this issue. Thanks. 👍🏽

![image](https://github.com/user-attachments/assets/1780f107-75f7-4e0e-bf18-822e5a415569)

**Comment by andriysavin** [comment]
I don't think this issue should be closed. I observe the same problems with virtio-sound-device, while virtio-sound-pci works. My understanding is that these are different kinds of paravirtualized sound device, virtio-sound-device being more "pure" and modern type which doesn't use PCI for device discovery. If I can choose virtio-sound-device in the list then it should work, otherwise what's the point?
